### ISSUE TITLE
Version 4.13.2 causes the most recent version of HA to crash

### ISSUE THREAD

**Issue by RadDip** [alandtse/alexa_media_player#2586] opened 2024-10-03 19:45 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

When upgrading to the latest Version of Alexa Media Player it causes HA to crash.  

**To Reproduce**

  Reinstalled HAOS on RPI4 (3) times and then installed the Alexa plugin update and HA crashed all (3) times.    Reinstalled HAOS in RPI4 a 4th time and system is stable and has not crashed

**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version: Core
2024.10.0
Supervisor
2024.09.1
Operating System
13.1
Frontend
20241002.2

- alexa_media version (from `const.py` or HA startup log):
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by azafred** [comment] 2024-10-03 19:58
I can confirm that the same thing happened to me this morning, right after restarting HA post upgrade (This package was the only thing upgraded) and Ha went into a crashloop.

**Comment by mremedi2023** [comment] 2024-10-03 19:59
Same here...I can no longer access the graphical interface

**Comment by mremedi2023** [comment] 2024-10-03 20:05
If I do a pin to the HA IP it responds, I put a monitor and I see it online, but I can't access it from anywhere else, I guess it was this update

**Comment by Jojo-A** [comment] 2024-10-03 20:07
Duplicate of #2579

**Comment by ISilvaPT** [comment] 2024-10-03 20:09
Same here, had to revert to prior version to stop HA from crashing.

**Comment by necromedias** [comment] 2024-10-03 20:09
Same problem. Disableing the alexa mediaplayer stopps the continous restarts.

**Comment by kurim** [comment] 2024-10-03 20:09
Can confirm have issue also.

Since mine crashed very often i decide to reinstall it complet HA.
At the point of reinstall the Alexa Addon the system begin to crash

**Comment by Jojo-A** [comment] 2024-10-03 20:10
Are you sure that you are talking about Version 4.13.2 and not 4.13.3?

**Comment by Jojo-A** [comment] 2024-10-03 20:12
@RadDip Please close this issue because it is a duplicate of #2579 .

**Comment by upholland** [comment] 2024-10-03 20:13
I am facing the same problem this morning with version 14.13.3

**Comment by Jojo-A** [comment] 2024-10-03 20:13
> I am facing the same problem this morning with version 14.13.3
EVERYONE:
Check out #2579

**Comment by Fadi-Shweiki** [comment] 2024-10-03 20:16
same for me > i mange to login for a few minutes until all services start, i disabled the integration, let see what happens

**Comment by mremedi2023** [comment] 2024-10-03 20:31
Please remove the new version as soon as possible, many people are left without access to their Home Assistant

**Comment by mremedi2023** [comment] 2024-10-03 20:32
4.13.2 work well, the problems is with 4.13.3

**Comment by suprra** [comment] 2024-10-03 20:40
@RadDip 
Please close the issue as it's a duplicate of https://github.com/alandtse/alexa_media_player/issues/2579#issue-2563215645

For those not checking the other issues for solutions
1. Disable alexa media player as soon as you get back in
2. Head to hacs and find alexa, hit the 3 dots in top right
3. Redownload different version 4.13.2

**Comment by SGXander** [comment] 2024-10-03 20:42
just had this too. thank god for snapshots. HASS entered a death loop

**Comment by weirded** [comment] 2024-10-03 21:28
Encountered this also - haven't debugged further but it seems to sit at 100% CPU and allocate tons of memory. Eventually, it gets OOMKilled: 

```
[ 1495.128348] Out of memory: Killed process 21259 (python3) total-vm:133768296kB, anon-rss:28761660kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:61028kB oom_score_adj:-300
```

My HA box has 32GB of memory but I saw it take up to > 90GB (using swap). 

Hope this helps point devs in the right direction.

**Comment by Ellevix** [comment] 2024-10-03 22:31
I can also confirm the latest version causes HAOS to crash, it puts HAOS in an endless loop of crashing, rebooting, crashing again. I had to revert to a backup of HAOS to resolve.

**Comment by danielbrunt57** [comment] 2024-10-03 22:54
duplicate of [issue #2579](https://github.com/alandtse/alexa_media_player/issues/2579)

**Closed by danielbrunt57** 2024-10-03 22:54 UTC
