### ISSUE TITLE
[Solved] Installation keeps looping the login page

### ISSUE THREAD

**Issue by just370z** [alandtse/alexa_media_player#2517] opened 2024-09-12 01:33 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Setup via amazon.com, will endlessly loop through the amazon login screen, it never progresses beyond inputting password.

**To Reproduce**

Installing

**Expected behavior**

shows installed integration

**Screenshots**

<img width="427" alt="366680437-8597af65-ffec-4d87-8cb3-fdda4d35b871" src="https://github.com/user-attachments/assets/8d60cf98-4a07-456c-9826-8f8024de5542">

![image](https://github.com/user-attachments/assets/f87df7c7-a9f1-4ab6-ab8c-6278c8d3ab57)

**System details**

- Home Assistant version: 2024.9.1
- alexa_media version (from `const.py` or HA startup log):  v4.12.12
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): Y
- Amazon Domain: amazon.com

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
 
see attached, it was too big to include
[AMP Debug log.txt](https://github.com/user-attachments/files/16972110/AMP.Debug.log.txt)

**Comment by MichaelB2018** [comment] 2024-09-12 01:41
I have the exactly same issue today

**Comment by just370z** [comment] 2024-09-12 01:52
Hopefully there is someone that can help us out there

**Comment by doctorkb** [comment] 2024-09-12 02:02
+1 - I thought it was just me... :(

**Comment by dangerzau** [comment] 2024-09-12 02:18
Same issue here to attempting to login to amazon.com.au so not just .com either :(  difference being - I had included configuring the internal 2FA - now up to 4 devices with the failed attempts using different pc's etc :p

**Comment by Onlyhanz-com** [comment] 2024-09-12 02:34
Im also having this issue, im new to HA and need this integration

**Comment by Onlyhanz-com** [comment] 2024-09-12 02:57
> Im also having this issue, im new to HA and need this integration

This solution was found posted by another on a 3 day old post and I am pasting them here as it solved my issue.

>Through trial and error trying to figure out the flow sequence, I was able to trick it and get to the OTP window.
After you've cycled through name, password and back to name, select the option Create Account New to Amazon?
Fill in a first & last name (anything at all as not going to matter so "Q W" is quick and easy to type!)
Amazon will then inform you that an account with your email already exists.
At that point re-select "Sign in Already a customer?" and proceed with the email and password windows and then the OTP window should appear. By that point though, the integration generated OTP has likely expired but you can just enter your current app generated OTP code and it should work.
If it returns to the integration add window and it just sits and spins and never progresses, that likely means the proxy listening session has expired and you'll have to repeat the process.

I am new to Github so I am not sure if this is the correct way to pass along a solution but this is my best attempt.

**Comment by Onlyhanz-com** [comment] 2024-09-12 02:57
@just370z

**Comment by doctorkb** [comment] 2024-09-12 03:01
Thanks @Onlyhanz-com ! That worked for me!

The only other step I'd add is that I had to reload the integration entry for it to find my devices.

**Comment by ldelvalleh** [comment] 2024-09-12 12:27
Thanks @Onlyhanz-com 

It worked for me, thanks a lot for the information.

**Comment by SmartHomeDIY** [comment] 2024-09-12 13:44
Thanks @Onlyhanz-com 

It also worked for me.

**Comment by regisleclerc** [comment] 2024-09-12 15:17
Same for me, I'm not alone 🙏

**Comment by bedge117** [comment] 2024-09-12 15:33
Came here to say bingo! The workaround worked for me. 

Login loop successfully broken and I have all my devices back.

**Comment by regisleclerc** [comment] 2024-09-12 16:24
+1 for the workaround, you rock @Onlyhanz-com 👏

**Comment by just370z** [comment] 2024-09-12 22:34
This worked for me as well, to get out of the login loop.
But it did not work the first try, the first try i got the 500 error, so i then reset my Amazon password and followed the installation steps and then your steps and it worked!
thank you again @Onlyhanz-com, great community!

**Comment by MichaelB2018** [comment] 2024-09-12 22:47
+1 for the workaround, thanks @Onlyhanz-com 👏

**Comment by OldAssComputer** [comment] 2024-09-13 01:20
Thank you for that work around.  I just started playing with this integration and thought something on my end was wrong.

**Comment by jeannicolasreyt** [comment] 2024-09-13 02:17
@Onlyhanz-com No clue how you figured it out, but it worked for me 🙏

**Comment by qu4nd** [comment] 2024-09-13 06:32
Tried the workaround and the login seemed to work.
Then I got this popup:
![Screenshot from 2024-09-13 08-30-48](https://github.com/user-attachments/assets/447cb3fe-d4d1-45d4-a0ba-112a7b05dbf3)

But the integration is not there.

**Comment by jamestas** [comment] 2024-09-14 09:15
> > Im also having this issue, im new to HA and need this integration
> 
> This solution was found posted by another on a 3 day old post and I am pasting them here as it solved my issue.
> 
> > Through trial and error trying to figure out the flow sequence, I was able to trick it and get to the OTP window.
> > After you've cycled through name, password and back to name, select the option Create Account New to Amazon?
> > Fill in a first & last name (anything at all as not going to matter so "Q W" is quick and easy to type!)
> > Amazon will then inform you that an account with your email already exists.
> > At that point re-select "Sign in Already a customer?" and proceed with the email and password windows and then the OTP window should appear. By that point though, the integration generated OTP has likely expired but you can just enter your current app generated OTP code and it should work.
> > If it returns to the integration add window and it just sits and spins and never progresses, that likely means the proxy listening session has expired and you'll have to repeat the process.
> 
> I am new to Github so I am not sure if this is the correct way to pass along a solution but this is my best attempt.

Thanks for this, I have my sanity back!
Workaround works!

**Comment by lucaxxaa** [comment] 2024-09-14 16:46
Thank...work now 💯

**Comment by danielbrunt57** [comment] 2024-09-15 08:16
> @Onlyhanz-com No clue how you figured it out, but it worked for me 🙏

I'm the one who figured it out and it was just a happy accident!  I wanted to see if that page was really talking to Amazon so I chose create new account which proved it was. But after that, it showed email & password in the same window which then led to the OTP window.  Now If I could only accidentally fix the initial window with email only that would be awesome!

**Comment by danielbrunt57** [comment] 2024-09-15 11:57
Duplicate of issue #2514

**Closed by danielbrunt57** 2024-09-15 11:57 UTC

**Comment by justinruaya123** [comment] 2024-10-06 12:52
I've tried this method and it redirects me to 3 methods: 

> > Im also having this issue, im new to HA and need this integration
> 
> This solution was found posted by another on a 3 day old post and I am pasting them here as it solved my issue.
> 
> > Through trial and error trying to figure out the flow sequence, I was able to trick it and get to the OTP window.
> > After you've cycled through name, password and back to name, select the option Create Account New to Amazon?
> > Fill in a first & last name (anything at all as not going to matter so "Q W" is quick and easy to type!)
> > Amazon will then inform you that an account with your email already exists.
> > At that point re-select "Sign in Already a customer?" and proceed with the email and password windows and then the OTP window should appear. By that point though, the integration generated OTP has likely expired but you can just enter your current app generated OTP code and it should work.
> > If it returns to the integration add window and it just sits and spins and never progresses, that likely means the proxy listening session has expired and you'll have to repeat the process.
> 
> I am new to Github so I am not sure if this is the correct way to pass along a solution but this is my best attempt.

Does not work. I've tried both (a) internal IP (192.168.xx) and (b) nabu casa link. The integration just refuses to work.

![image](https://github.com/user-attachments/assets/3640dab0-e47b-4b81-8a76-238f68679d4d)

**Comment by Suleiman700** [comment] 2024-10-24 16:06
I've been trying to fix this issue for the last 2 weeks.
Tried enabling 2FA and disabling it ...etc, But nothing worked!

The solution is:
1. Change amazon account
2. HA -> Add device -> Alexa media player
3. Enter email & password & URL to home assistant (I've used local and public URLs)
4. Pressed continue and it opened amazon login
5. Clicked on register and entered random text in the name and clicked continue
6. It said a email already exists, I clicked login
7. Entered email & password and clicked login
8. A new page asking for OTP
9. Entered OTP from the 2FA app (Google Authentication)

And now finally it works

**Comment by adamtiley** [comment] 2024-10-31 09:50
When I do this, it seems to give me a captcha and then upon correctly entering it, it throws a 500 internal sever error (server got itself in trouble)

Any ideas?

**Comment by patrickblau90** [comment] 2024-10-31 19:50
> When I do this, it seems to give me a captcha and then upon correctly entering it, it throws a 500 internal sever error (server got itself in trouble)
> 
> Any ideas?

For me, i had to enable 2FA verification and than it worked, no 500 internal error, integration moved further.

**Comment by adamtiley** [comment] 2024-11-01 00:30
> > When I do this, it seems to give me a captcha and then upon correctly entering it, it throws a 500 internal sever error (server got itself in trouble)
> > Any ideas?
> 
> For me, i had to enable 2FA verification and than it worked, no 500 internal error, integration moved further.

OH MY GOD. I thought it was already enabled cause I linked my authenticator up with it, but I went into "Login & Security" settings and it wasn't on!?

Turned it on and the captcha didn't show up and in its place, the OTP did! FANTASTIC!

Thanks so much for the nudge in the right direction! 😊

**Comment by arierep60** [comment] 2025-05-12 15:58
> I've been trying to fix this issue for the last 2 weeks. Tried enabling 2FA and disabling it ...etc, But nothing worked!
> 
> The solution is:
> 
> 1. Change amazon account password
> 2. HA -> Add device -> Alexa media player
> 3. Enter email & password & URL to home assistant (I've used local and public URLs)
> 4. Pressed continue and it opened amazon login
> 5. Clicked on register and entered random text in the name and clicked continue
> 6. It said a email already exists, I clicked login
> 7. Entered email & password and clicked login
> 8. A new page asking for OTP
> 9. Entered OTP from the 2FA app (Google Authentication)
> 
> And now finally it works

Tried that and always get 404: Not Found or 500 Internal Server Error
Server got itself in trouble

Any tips?
