### ISSUE TITLE
PLEASE REVOKE v4.13.3 ASAP!

### ISSUE THREAD

**Issue by Jpsy** [alandtse/alexa_media_player#2583] opened 2024-10-03 18:17 UTC
**Describe the bug**

v4.13.3 is obviously breaking complete HA installations by the dozens - or more likely though: by the thousands, with new systems affected every moment.

Please revoke this release ASAP until a fix is available. 
**Thanks for all your work and sorry for yelling... ;D**

See:
#2582
#2579 
https://github.com/home-assistant/core/issues/127431
https://github.com/home-assistant/core/issues/127460
https://github.com/home-assistant/core/issues/127395
(and probably more to come soon)

**Comment by mafmafmafmaf** [comment] 2024-10-03 19:01
As a newbie, this was a nightmare to me. I upgraded AMP, then got in the disconnect loop... had no idea what was going on... tried to see on the logbook - "Repairs detected an event" with other details, thanks a lot... googled for that expression, result: unknown... back to Settings, noticed the Tip! Went to the forums, and here I am. I have already downgraded AMP but why is the faulty version still being offered? Take it down ASAP please!

**Comment by liviumac** [comment] 2024-10-03 19:20
I just spent 3 hours trying to understand why my HA is not repsonding / restarting randomly and explaining to my family why the lights and well... nothing really works anymore :-)

It is only after I disabled the recently updated Alexa integration that my system became stable again (fingers crossed).

We appreciate your work, but this needs to be fixed. Thank you!

**Comment by roeberp** [comment] 2024-10-03 19:39
Same thing here. Endless frustration this morning as my HA rebooted constantly. I restored from a backup early this AM (before the AMP update) and everything was fine. "Skipped" the update for now.

**Comment by kmil4** [comment] 2024-10-03 19:43
Oh so this is why. 

Ugh. What a shit show. My only option is to restore form backup? Come on guysssss

**Comment by azafred** [comment] 2024-10-03 19:59
yep... had to restore from last backup as well...

**Comment by upholland** [comment] 2024-10-03 20:14
Facing the same problem, HA keeps crashing when updated Alexa media player to version 14.13.3

**Comment by Fadi-Shweiki** [comment] 2024-10-03 20:23
if u mange to login to hasso disable it it or downgrade

**Comment by simonk1969** [comment] 2024-10-03 20:28
Same issue here, spent ages trying to figure it out until I found this :-(

**Comment by suprra** [comment] 2024-10-03 20:31
For those not reading the other issues posted.
1. Disable the integration
2. Head to hacs and click the 3 dots top right
3. Redownload and choose a 4.13.2

**Comment by jnpetersen** [comment] 2024-10-03 23:10
I had the same issue, but I could never get into HA long enough to be able to disable and re-download.  I ended up ssh'ing into the server, went to the custom_components folder and moved it out do a directory not within HA for the time being to see if that was what was causing it.  Once moved out, I was able to start HA successfully and re-download.

**Comment by J0nnyBr4v0** [comment] 2024-10-03 23:44
took me age to identify the issue. Thanks for reporting ;)

**Comment by lsellens** [comment] 2024-10-04 01:09
This is the only integration I have that ever breaks and it does often. Why not setup a beta channel and actually test the changes before rolling them out? I'd be happy to help test.

**Comment by alandtse** [comment] 2024-10-04 02:32
We don't need testers per se, we need devs.

Dupe of #2579.

**Closed by alandtse** 2024-10-04 02:32 UTC

**Comment by PJLLB** [comment] 2024-10-04 06:50
It appears they have pulled 4.13.3.
