### ISSUE TITLE
HA startup issue: "Error while setting up alexa_media platform for sensor"

### ISSUE THREAD

**Issue by jkfranks9** [alandtse/alexa_media_player#2221] opened 2024-03-27 13:22 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

When starting HA I always see an exception for: AttributeError: 'NoneType' object has no attribute 'data'

**To Reproduce**

Happens once on every HA start.

**Expected behavior**

No exception logged.

**Screenshots**

**System details**

- Home-assistant (version): 2024.3.3
- alexa_media (version from `const.py` or HA startup): 4.9.2
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**
```
2024-03-27 08:30:51.286 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 358, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 630, in async_add_entities
    or not any(entity.should_poll for entity in entities)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 630, in <genexpr>
    or not any(entity.should_poll for entity in entities)
               ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/sensor.py", line 591, in should_poll
    return not (self.hass.data[DATA_ALEXAMEDIA]["accounts"][self._account]["http2"])
                ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
```
[home-assistant_alexa_media_2024-03-27T12-46-47.304Z.log](https://github.com/alandtse/alexa_media_player/files/14773896/home-assistant_alexa_media_2024-03-27T12-46-47.304Z.log)

**Additional context**

**Comment by ancientm74** [comment] 2024-03-30 14:59
Same problem

**Comment by alandtse** [comment] 2024-04-06 18:14
Dupe of #2200

**Closed by alandtse** 2024-04-06 18:14 UTC
Labels: duplicate
