### ISSUE TITLE
Warnings and Errors in HA log

### ISSUE THREAD

**Issue by def1149** [alandtse/alexa_media_player#2245] opened 2024-05-02 14:13 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Multiple Alexa integration errors in the log

**To Reproduce**

None, errors occur without user action

**Expected behavior**

No errors

**Screenshots**

N/A

**System details**

- Home-assistant (version): 2404.5.0
- alexa_media (version from `const.py` or HA startup): 4.9.2
- alexapy (version from `pip show alexapy` or HA startup): ??
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). No
- 
**Logs**

```
2024-05-01 21:00:54.275 WARNING (SyncWorker_26) [homeassistant.helpers.frame] Detected that custom integration 'alexa_media' calls async_write_ha_state from a thread at custom_components/alexa_media/switch.py, line 217: self.async_write_ha_state(), please report it to the author of the 'alexa_media' custom integration
2024-05-01 21:00:54.295 WARNING (SyncWorker_14) [homeassistant.helpers.frame] Detected that custom integration 'alexa_media' calls async_write_ha_state from a thread at custom_components/alexa_media/switch.py, line 217: self.async_write_ha_state(), please report it to the author of the 'alexa_media' custom integration
2024-05-01 21:00:54.534 ERROR (SyncWorker_14) [homeassistant.util.logging] Exception in _handle_event when dispatching 'alexa_media_*******@*******': ({'queue_state': {'dopplerId': {'deviceSerialNumber': 'G2A0QXXXXXXXXX', 'deviceType': 'A7WXQPH584YP'}, 'changeType': 'NEW_QUEUE', 'playBackOrder': 'NORMAL', 'loopMode': 'NORMAL', 'trackOrderChanged': False, 'destinationUserId': 'A2A8XZZZZZZZZ'}},)
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/switch.py", line 217, in _handle_event
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'alexa_media' calls async_write_ha_state from a thread at custom_components/alexa_media/switch.py, line 217: self.async_write_ha_state(). Please report it to the author of the 'alexa_media' custom integration.

2024-05-01 21:00:54.535 ERROR (SyncWorker_26) [homeassistant.util.logging] Exception in _handle_event when dispatching 'alexa_media_*******@******': ({'queue_state': {'dopplerId': {'deviceSerialNumber': 'G2A0QXXXXXXXX', 'deviceType': 'A7WXQPH584YP'}, 'changeType': 'NEW_QUEUE', 'playBackOrder': 'NORMAL', 'loopMode': 'NORMAL', 'trackOrderChanged': False, 'destinationUserId': 'A2A8X2XXXXXXXX'}},)
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/switch.py", line 217, in _handle_event
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'alexa_media' calls async_write_ha_state from a thread at custom_components/alexa_media/switch.py, line 217: self.async_write_ha_state(). Please report it to the author of the 'alexa_media' custom integration.


2024-05-01 22:15:56.498 ERROR (MainThread) [alexapy.alexaapi] Giving up _static_request(...) after 5 tries (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
2024-05-01 22:15:56.498 WARNING (MainThread) [alexapy.helpers] alexaapi.get_customer_history_records((<alexapy.alexalogin.AlexaLogin object at 0x7f8a9a1a30>,), {'max_record_size': 10}): An error occurred accessing AlexaAPI: An exception of type AlexapyTooManyRequestsError occurred. Arguments:
('Too Many Requests',)
2024-05-01 22:15:56.499 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f8a9a1a30>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyTooManyRequestsError occurred. Arguments:
('Too Many Requests',)
2024-05-01 22:15:56.500 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: Too Many Requests
```

**Additional context**
There are hundreds of lines of this in the log

**Comment by alandtse** [comment] 2024-05-06 03:21
Thanks. The runtimerror is addressed by #2250. Too many requests is a dupe of #2177. Please follow that.

**Closed by alandtse** 2024-05-06 03:21 UTC
Labels: duplicate
