### ISSUE TITLE
After 2024.12.0 update - Setup failed for custom integration 'alexa_media': Requirements for alexa_media not found: ['alexapy==1.29.4'].

### ISSUE THREAD

**Issue by gavinpbennett** [alandtse/alexa_media_player#2716] opened 2024-12-04 20:17 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
After updating to 2024.12.0 update, I receive the following error in the logs.:

Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 09:11:51 (3 occurrences)
Last logged: 09:11:55

Unable to install package alexapy==1.29.4: × No solution found when resolving dependencies: ╰─▶ Because alexapy==1.29.4 depends on aiofiles>=23.1.0,<24.0.0 and aiofiles>=24.1.0, we can conclude that alexapy==1.29.4 cannot be used. And because you require alexapy==1.29.4, we can conclude that your requirements are unsatisfiable.

**Comment by garfieldjsmith** [comment] 2024-12-04 20:20
This has already been reported.

**Comment by tporteus** [comment] 2024-12-04 20:26
https://github.com/alandtse/alexa_media_player/issues/2698

**Comment by Drummingman** [comment] 2024-12-04 21:15
Same Here

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 22:03:12 (1 occurrences)
Last logged: 22:03:12

Setup failed for custom integration 'alexa_media': Requirements for alexa_media not found: ['alexapy==1.29.4'].

**Comment by Moonbase59** [comment] 2024-12-04 21:33
Same here:

```
Logger: homeassistant.setup
Quelle: setup.py:269
Erstmals aufgetreten: 22:29:37 (1 Vorkommnisse)
Zuletzt protokolliert: 22:29:37

Setup failed for custom integration 'alexa_media': Requirements for alexa_media not found: ['alexapy==1.29.4'].
```

**Comment by abjwsm** [comment] 2024-12-04 21:51
I have the same issue. My Alexa Media is not loading since 2024.12.0 update

**Comment by MichaelStruck** [comment] 2024-12-04 22:03
Following this as it occurred to me. Rolling back to 2024.11.x fixes the issue for now

**Comment by kbrown01** [comment] 2024-12-04 22:37
Yep, agreed. 12.0 = "Kill Alexa" version

**Comment by realtek2017** [comment] 2024-12-05 00:09
I have the same issue too

**Comment by dspille** [comment] 2024-12-05 00:57
Same issue for me.

**Comment by soheiladeli** [comment] 2024-12-05 01:00
same issue here

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 11:34:21 AM (3 occurrences)
Last logged: 11:34:26 AM

Setup failed for custom integration 'alexa_media': Requirements for alexa_media not found: ['alexapy==1.29.4'].

**Comment by danielbrunt57** [comment] 2024-12-05 01:29
Duplicate of known issue

**Closed by danielbrunt57** 2024-12-05 01:29 UTC
