### ISSUE TITLE
ultrasonic motion detection 

### ISSUE THREAD

**Issue by fwmarcel** [alandtse/alexa_media_player#1741] opened 2022-09-29 12:58 UTC
Amazon recently allows motion detection through ultrasound.
See link: https://www.amazon.science/blog/the-science-behind-ultrasonic-motion-sensing-for-echo

For this reason, I would like to have a sensor for exactly this motion detection, in order to be able to use it additionally in Home Assistant.

**Comment by alandtse** [comment] 2022-10-02 08:58
Is it available in the Amazon Alexa app?

**Comment by alandtse** [comment] 2022-10-02 09:23
Dupe of #1736

**Comment by gaizaharduz** [comment] 2023-02-12 11:53
This is not a duplicate of #1736. Could we please reopen it?

These are two very different features of Alexa. That one detects specific sounds (baby crying, appliance beeping, etc.) This one detects motion using ultrasound.

**Comment by gaizaharduz** [comment] 2023-04-15 18:22
The feature request is still relevant.

**Comment by Hackashaq666** [comment] 2023-04-26 11:46
> Amazon recently allows motion detection through ultrasound. See link: https://www.amazon.science/blog/the-science-behind-ultrasonic-motion-sensing-for-echo
> 
> For this reason, I would like to have a sensor for exactly this motion detection, in order to be able to use it additionally in Home Assistant.

As a workaround:
I created a input boolean switch in home assistant (input_boolean.living_room_motion) and control it with routines in the alexa app.
“on” when people detected by living room echo dot.
“off” when people aren’t detected.

**Comment by fwmarcel** [comment] 2023-06-26 19:10
Is there any news here yet?
The workaround does work. Unfortunately it is not pretty...

**Comment by pvillanyi** [comment] 2023-08-31 19:14
> Dupe of #1736

It's not dupe.
Sound recognition and ultrasonic motion detection isn't the same.
Altough it would be nice if both were exposed in HA

**Comment by alandtse** [comment] 2023-08-31 19:57
You realize that I removed the duplicate tag and reopened it like months ago based on this [comment](https://github.com/custom-components/alexa_media_player/issues/1741#issuecomment-1427012864) right?

**Comment by pvillanyi** [comment] 2023-08-31 20:13
I didn't read every comment.
My aim wasn't to talk bad on you.
I just want to keep this request alive.
It's strange this features aren't included

**Comment by Wolfieeewolf** [comment] 2023-09-12 07:15
As this is getting no love I thought I would see if I could get something to work. I have limited programming knowledge but reading over the code I found a few things that could possibly be added that might get this working. 

I haven't been able to get it to work yet but maybe someone with a bit more knowledge might be able to guide me.

I just copied the temperature sensor code and changed a few things. I looked over most of the files but I'm sure I'm missing some code here and there.

So far I have added the following lines to alexa_entity.py. 

```
def is_motion_sensor(appliance: dict[str, Any]) -> bool:
    """Is the given appliance the motion sensor of an Echo."""
    return is_local(appliance) and has_capability(
        appliance, "Alexa.MotionSensor", "motion"
```

I have also added some lines to sensor.py

```
from .alexa_entity import (
    parse_air_quality_from_coordinator,
    parse_temperature_from_coordinator,
    parse_motion_from_coordinator,
```

```
    motion_sensors = []
    motion_entities = account_dict.get("devices", {}).get("motion", [])
    if motion_entities and account_dict["options"].get(
        CONF_EXTENDED_ENTITY_DISCOVERY
    ):
        motion_sensors = await create_motion_sensors(
            account_dict, motion_entities
        )

    return await add_devices(
        hide_email(account),
        devices + temperature_sensors + air_quality_sensors + motion_sensors,
        add_devices_callback,
        include_filter,
        exclude_filter,
```

```
async def create_motion_sensors(account_dict, motion_entities):
    """Create motion sensors."""
    devices = []
    coordinator = account_dict["coordinator"]
    for temp in motion_entities:
        _LOGGER.debug(
            "Creating entity %s for a motion sensor with name %s",
            temp["id"],
            temp["name"],
        )
        serial = temp["device_serial"]
        device_info = lookup_device_info(account_dict, serial)
        sensor = MotionSensor(coordinator, temp["id"], temp["name"], device_info)
        account_dict["entities"]["sensor"].setdefault(serial, {})
        account_dict["entities"]["sensor"][serial]["Temperature"] = sensor
        devices.append(sensor)
    return devices
```


This is the code that I think is the issue. I'm not sure what to put here

```
class MotionSensor(SensorEntity, CoordinatorEntity):
    """A motion sensor reported by an Echo."""

    def __init__(self, coordinator, entity_id, name, media_player_device_id):
        """Initialize motion sensor."""
        super().__init__(coordinator)
        self.alexa_entity_id = entity_id
        self._attr_name = name + " Motion"
        self._attr_device_class = SensorDeviceClass.MOTION
        self._attr_state_class = SensorStateClass.VALUE
        self._attr_native_value: Optional[
            datetime.datetime
        ] = parse_motion_from_coordinator(coordinator, entity_id)
        self._attr_native_value: Optional[str] = detectionState.VALUE
        self._attr_unique_id = entity_id + "_motion"
        self._attr_device_info = (
            {
                "identifiers": {media_player_device_id},
                "via_device": media_player_device_id,
            }
            if media_player_device_id
            else None
        )

    @callback
    def _handle_coordinator_update(self) -> None:
        """Handle updated data from the coordinator."""
        self._attr_native_value = parse_temperature_from_coordinator(
            self.coordinator, self.alexa_entity_id
        )
        super()._handle_coordinator_update()
```

Not sure if

```
self._attr_device_class = SensorDeviceClass.MOTION
self._attr_state_class = SensorStateClass.VALUE
```
and 

`self._attr_native_value: Optional[str] = detectionState.VALUE`

are correct this could be the issue but I have no idea.  As I said I have limited programming knowledge and was just seeing if adding this would work. 

Hopefully, this gets fixed soon. The documentation on the [Alexa Development](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-motionsensor.html) page might be the answer to the puzzle.

**Comment by eporsche** [comment] 2023-11-02 09:02
Here is a workaround for anyone interested. 

Prerequisites: 
Emulated Hue enabled

1) Create an input boolean 
2) Publish the input boolean via emulated hue
3) Create two routines in Alexa. One that will switch the input boolean to "on" if motion has been detected. One which will switch the input boolean to "off" if no motion has been detected.
4) Know you can create automations based on the state of the input boolean in home assistant

The cooldown phase of the ultrasonic sensor in alexa echo devices is 30 minutes and this cannot be changed.
Therefore the input boolean will only trigger once every 30 minutes and not in between.

https://www.amazon.com/gp/help/customer/display.html?nodeId=G9ECYL5AQBAQ4F2L

**Closed** 2024-01-13 02:06 UTC
Labels: enhancement, help wanted, question, no-issue-activity
