### ISSUE TITLE
Alexa Media causes runtime error after upgrade to 4.10.2

### ISSUE THREAD

**Issue by tbclark3** [alandtse/alexa_media_player#2295] opened 2024-06-30 03:40 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After upgrading to 4.10.2, I started getting runtime errors.  It doesn't happen for several hours after startup. Twice it has locked up my HA instance. Each time, the instance was spitting out continuous errors, but was not responding to HTTP requests and was not processing input.

**To Reproduce**

Upgrade to 4.10.2 and run for several hours.

**Expected behavior**

Release 4.10.2 should run withour errors.

**Screenshots**

**System details**

- Home-assistant (version): 2024.6.4
- alexa_media (version from `const.py` or HA startup): 4.10.2
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
raise RuntimeError(
RuntimeError: Detected that custom integration 'alexa_media' calls hass.bus.async_fire from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassbusasync_fire at custom_components/alexa_media/sensor.py, line 433: self.hass.bus.async_fire(. Please report it to the author of the 'alexa_media' custom integration.

**Additional context**

Release 4.10.2 doesn't fix the failure to load the integration on startup.

**Comment by alandtse** [comment] 2024-06-30 06:26
Dupe of #2264

**Closed by alandtse** 2024-06-30 06:26 UTC
