### ISSUE TITLE
Detected that custom integration 'alexa_media' accesses hass.components.group. This is deprecated and will stop working in Home Assistant 2024.9

### ISSUE THREAD

**Issue by javiges** [alandtse/alexa_media_player#2230] opened 2024-04-08 13:04 UTC
To Reproduce

Start HA.

Expected behavior

The component should work.

**System details**

- Home-assistant (version): 
Home asistant Container;
Core: 2024.4.0
- alexa_media (version from `const.py` or HA startup): v4.9.2

- alexapy (version from `pip show alexapy` or HA startup): I don't know how I can get this, it is not printed in the HA startup logs

- Amazon [2FA is enabled]: yes

**Logs**

Detected that custom integration 'alexa_media' accesses hass.components.group. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from group directly at custom_components/alexa_media/notify.py, line 240: entities.extend(self.hass.components.group.expand_entity_ids(entities)), please create a bug report at https://github.com/alandtse/alexa_media_player/issues

**Comment by drizuid** [comment] 2024-04-13 23:25
dupe of #2229

**Closed** 2024-04-21 11:35 UTC
Labels: duplicate
