### ISSUE TITLE
Alexa Media Player fails to start after restarting HA 2024.6.3

### ISSUE THREAD

**Issue by macroysan** [alandtse/alexa_media_player#2290] opened 2024-06-19 22:02 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version):
- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by DanrwAU** [comment] 2024-06-22 02:41
Seeing similar issues with failing to start. 

Restarting does fix it 

```
2024-06-22 12:39:07.053 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry myemail - amazon.com.au for alexa_media
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/alexa_media/__init__.py", line 335, in async_setup_entry
await login.login(cookies=await login.load_cookie())
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 328, in load_cookie
cookies = pickle.loads(await myfile.read())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/http/cookies.py", line 312, in __setitem__
raise CookieError("Invalid attribute %r" % (K,))
http.cookies.CookieError: Invalid attribute 'partitioned'
```

**Comment by jum0n** [comment] 2024-06-22 13:21
Mine fails after every HA restart.  If I manually restart later, it works until the next restart then fails to start again.  Is that the same behavior each of you have?

**Comment by Menz01** [comment] 2024-06-22 16:49
for me... every time I restart HA it shows failed but if i go to the integration and click reload, it starts working

**Comment by TarheelGrad1998** [comment] 2024-06-22 17:16
Same issue, with the partitioned error.  As a workaround, I have implemented an automation that fixes it for now (below, replace with one of your Alexa media players).

```
alias: "Alexa Media: Keep Online"
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.den_echo
    to: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
action:
  - service: homeassistant.reload_config_entry
    target:
      entity_id: media_player.den_echo
    data: {}
mode: single

```

**Comment by bozzobrain** [comment] 2024-06-22 18:19
Same issue here. Restart HA and Alexa Media Player failed to setup. Reloading the integration appears to permanently fix the setup until the next restart of HA.

Log

```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 2:08:55 PM (1 occurrences)
Last logged: 2:08:55 PM

Error setting up entry email@gmail.com - amazon.com for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 335, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 328, in load_cookie
    cookies = pickle.loads(await myfile.read())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/cookies.py", line 312, in __setitem__
    raise CookieError("Invalid attribute %r" % (K,))
http.cookies.CookieError: Invalid attribute 'partitioned'
```

**Comment by simonk1969** [comment] 2024-06-22 23:13
Isn't this a duplication of #2288 ?

https://github.com/alandtse/alexa_media_player/issues/2288

**Comment by danielbrunt57** [comment] 2024-06-26 14:54
> Isn't this a duplication of #2288 ?

Yes it is.

**Comment by danielbrunt57** [comment] 2024-07-10 02:42
@alandtse Please close this issue as it a duplicate of https://github.com/alandtse/alexa_media_player/issues/2288

**Comment by danielbrunt57** [comment] 2024-07-11 15:12
@alandtse Please close this issue as it a duplicate of https://github.com/alandtse/alexa_media_player/issues/2288
It is a problem with alexapy and HA > 2024.6.2 for which there is no solution until Python 3.13 is released with partitioned cookie support - ETA October, and HA sometime after that (unless you can rewrite alexapy to work around it!).

**Closed** 2024-07-11 15:14 UTC

**Comment by Eproom** [comment] 2024-08-25 14:21
Buenas tardes a todos, creo que tengo el mismo problema desde España, cuando lo reconfiguro funciona bien por un tiempo relativamente corto hasta que interactuamos con Alexa media Player y vuelve a dar error, no puedo vivir si esta aplicación, darme una solucion por favor
