### ISSUE TITLE
Authentication failure / Internal Server Error 500

### ISSUE THREAD

**Issue by nsleigh** [alandtse/alexa_media_player#2201] opened 2024-03-02 15:34 UTC
**Describe the bug**
My integration has been working perfectly for a long time but today I upgrade and it has started failing initial just with and error message saying it "failed" (sorry that is vague as I have lost that now).

So I decided to delete the integration and start again following this: https://github.com/alandtse/alexa_media_player/wiki/Configuration#built-in-2fa-app

The OTA auth seems to work but then I get a web page where I have to enter a CAPTCHA - no matter what I try I get "500 Internal Server Error Server got itself in trouble" (sometimes this appears before I even get time to enter the CAPTCHA.

**To Reproduce**

Follow the Built-in 2FA App instructions.

**Expected behavior**

Integration is setup.

**Screenshots**

**System details**

- Home-assistant (version): 2024.2.5
- alexa_media (version from `const.py` or HA startup): 4.9.2
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes:
- Amazon domain: amazon.co.uk

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

Will provide more logs if required but first I wanted to know if anyone else is having issues?
When following the instructions should the 2FA key include the spaces or not (I have tried both)?
Is there any alternative to the CAPTCHA - I really struggle to read these!

**Comment by nsleigh** [comment] 2024-03-02 15:49
I think I have it working now - I missunderstood the user/pwd the website was looking for. As it was on my HA instance I used the user/pwd but it clearly say the Amazon one!

Leave this here in case it helps anyone else.

**Comment by pollinolas** [comment] 2024-03-06 12:25
I'm having problems since yesterday with the authentication for the domain "amazon.es" as well. I receive many "Internal Server Error 500" messages after several attempts, sometimes it gives the captcha option, other times the login option and other times the verification with code, but in the end it always ends up giving the error "500" or "401 Unauthorized". I have deleted the integration, installed again, cleared cache, tried other browsers and it always ends up giving an error. I'm starting to wonder if the problem could come from another source, such as the attack on the submarine cables that occurred in the Red Sea, because I'm also having communication/lag problems in other integrations.

**Comment by pollinolas** [comment] 2024-03-07 02:12
I tried it a while ago after updating HAOS and it was authenticated the first time

**Comment by Kefut** [comment] 2024-03-09 13:13
Does not work for me at all. Tried to just install it with 2024.3 but always run into this>
![image](https://github.com/alandtse/alexa_media_player/assets/70171384/b9304b28-6d88-4cb7-90d9-ecc227d4a111)

**Comment by multinet33** [comment] 2024-03-09 19:34
Same here (amazon.fr)

**Comment by TheLinx79** [comment] 2024-03-10 10:04
Me too. I have passkeys enabled on my account. Not sure if that's it?

**Comment by pollinolas** [comment] 2024-03-10 15:05
I don't know what the problem could be, in my case I thought it was due to the servers, because that day many had failed (Facebook, Instagram, etc.) and always doing the same steps I had that error for more than 15 attempts, the next day I did it. I tried again without doing anything different and it worked the first time🤷🤷

**Comment by multinet33** [comment] 2024-03-21 22:15
Résolution : activate 2FA on Amazon account

**Comment by nsleigh** [comment] 2024-03-21 22:19
That wasn't the issue, it was already enabled.

**Comment by multinet33** [comment] 2024-03-21 22:22
I answered for my comment

**Comment by nsleigh** [comment] 2024-03-21 22:37
Sorry missed that.

**Comment by zer0point** [comment] 2024-03-22 07:16
Same here. (amazon.de)

Core: 2024.3.1
Supervisor : 2024.03.0
Operating System: 12.1
Frontend: 20240307.0

Alexa Media Player - v4.9.2
Amazon 2FA is enabled (y/n). Yes
Amazon domain: amazon.de

**Comment by miguepollo** [comment] 2024-03-22 17:17
Same problem :(

**Comment by miguepollo** [comment] 2024-03-22 17:20
Core: 2024.3.2
Supervisor : 2024.03.0
Operating System: 12.1
Frontend: 20240307.0

Alexa Media Player - v4.9.2
Amazon 2FA is enabled (y/n). Yes
Amazon domain: amazon.es

**Comment by miguepollo** [comment] 2024-03-22 17:20
Maybe try in amazon.com?

**Comment by miguepollo** [comment] 2024-03-22 17:24
No.Not working

**Comment by gonsanbo** [comment] 2024-03-22 18:23
same here

**Comment by DanielMisch** [comment] 2024-03-23 11:55
Same here since update. 2fa was working before. Now each reauth or uninstall and readd will end in error 500.

**Comment by alandtse** [comment] 2024-03-23 18:47
Dupe of #2138

**Closed by alandtse** 2024-03-23 18:47 UTC

**Comment by atzetot** [comment] 2024-04-22 14:22
Dear all
had this issues and tried almost everything mentioned in different forums.

In the end I check for 
`pip show alexapy` and apparently it was not installed hence I ran `pip install alexapy`.
Moreover I had created the 2FA in amazon with OTP via application as preferred and mobile as second.

I tried to register the integration via 
- Nabucase URL
- Cloudflare domain
- local IP 
via PC !!!
Nothing worked. Always captcha that returned the 500.

.Ultimately I used my mobile phone where I had my OTP goole authentificater..
.Logged into my local 192.168....:8123 home assistant URL
.started the ususal alexa media plugin intration
.entered my details and used the LAN URL
.amazon popped up with..... OTP request instead of captcha.
.entered OTP from google auth.

BAM. worked flawlessly.
Hope this works for you as well.
