### ISSUE TITLE
I tried many, many times, but could not install alexa_media_player on any of them. (500 Internal Server Error and infinite captcha)

### ISSUE THREAD

**Issue by hpoperator86** [alandtse/alexa_media_player#2152] opened 2023-12-29 16:35 UTC
**Describe the bug**

Hello dear Community/Hello dear developer,

I have been trying to implement the integration in HA for 4 hours now, unfortunately without success.
Many issues with the same or similar problems have already been published here and no post has helped me.

I have added alexa_media_player in HACS (latest version) and then restarted the HA system (installed in the latest version on a Nuc just a week ago). Then I went to the integrations and added alexa_media_player, the configurations opened.

Now there were several different effects
In my Firefox, I was taken directly to the Amazon login page, where the login data was already correctly stored (checked several times) I checked the box "stay logged in" and clicked on "log in" here I was redirected to a captcha, which I entered and when I clicked on continue I got a page that showed me: "500 Internal Server Error". No matter how many times I went back and refreshed the page, it was always the same result.
Exactly the same with my Android phone (with mobile data traffic AND data traffic via wifi).

The same with my son's iPhone!

With the Microsoft Edge browser too!

With the Google Chrome browser I get the same login page and the loyalty/design of the captcha page is different. On all other devices it is colored bluish, here it is in the yellowish Amzon colors. And here I find myself in an endless loop as far as the captcha is concerned. After each captcha entry, a new one appears. It continues ad infinitum. Here I tried the suggested solution that I read in a thread here and went back to the login page and pressed login again, but no matter how often and in what order I refreshed, the same result kept coming back!

I also tried with the Tor browser, exactly the same as with the Edge browser. Putting the different browsers into incognito mode also didn't help.

I also changed the "Home Assistant URL*" in the configuration input mask to my internal URL ( http://192.xxx.xxx.xx:8123/ ) and tried the same thing again that I had already done, but that didn't help either.

I also deactivated IPv6 in my router and tried everything again. Again, no success.

It almost seems as if the media player can no longer be installed.

Please help!

---Steps to reproduce the behavior:---

Here I entered the login data of my Amazon account (email/password) and changed the Amazon region to "amazon.de".
Under "Home Assistant URL*" my nabu.casa URL was automatically inserted, which is accessible from the outside.
For Integrated 2FA app key, I added the key generated by Amazon, which can be found under "My account --> Login and security --> Add a new phone or authentication app --> Cannot scan barcode? --> Point 3". I first deleted all the spaces between the alphanumeric groups and made sure that there were no spaces before or after the key.

Then I clicked on "Send", added the OTP code in Amzon (the same path where you received the key from Amazon) and confirmed on Amzon that verification had taken place.
I did the same in the HA configuration window by checking the box and confirming.

**System details**

- Home-assistant (version):  
Core 2023.12.4
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2
- alexa_media (version from `const.py` or HA startup): not installed
- alexapy (version from `pip show alexapy` or HA startup): not installed
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : 2FA is activated. look my procedure

**Logs**
i can't activate debbug-log because i can't get the player installed.

**Additional context**

**Comment by Undercoverbohne** [comment] 2023-12-29 21:26
same here infinite captcha

**Comment by alandtse** [comment] 2023-12-30 05:39
Dupe of #2138

**Closed by alandtse** 2023-12-30 05:39 UTC
