### ISSUE TITLE
CookieError: Invalid attribute 'partitioned'

### ISSUE THREAD

**Issue by membersound** [alandtse/alexa_media_player#2297] opened 2024-07-01 07:19 UTC
**Describe the bug**
Suddenly alexa integration is not availabile in automations anymore, without toughting HA. See logs below, has something to do with Cookies?

**To Reproduce**

Every other day the alexa addon is suddenly in state "failed to setup", even though I did not restart HomeAssistant!

**Expected behavior**
The component should start

**System details**

- Home-assistant (version): 2024.6.4
- alexa_media (version from `const.py` or HA startup): 4.10.2
- alexapy (version from `pip show alexapy` or HA startup): cannot figure out
- Amazon [2FA is enabled]: y

**Logs**
```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 3:30:38 AM (1 occurrences)
Last logged: 3:30:38 AM
Error setting up entry daniel_kotyk@hotmail.com - amazon.de for alexa_media

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 335, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 328, in load_cookie
    cookies = pickle.loads(await myfile.read())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/cookies.py", line 312, in __setitem__
    raise CookieError("Invalid attribute %r" % (K,))
http.cookies.CookieError: Invalid attribute 'partitioned'
```

**Comment by danielbrunt57** [comment] 2024-07-04 14:58
This is a duplicate of [#2290](https://github.com/alandtse/alexa_media_player/issues/2290)...

**Comment by myevit** [comment] 2024-07-06 22:37
Same issue, same logs. Had to roll back to previous release.

**Comment by danielbrunt57** [comment] 2024-07-10 02:40
@alandtse Could you please close this as it a duplicate of [issue #2288 ](https://github.com/alandtse/alexa_media_player/issues/2288
)

**Closed** 2024-07-10 03:20 UTC

**Comment by danielbrunt57** [comment] 2024-07-10 10:47
@alandtse 
Thank your!
New PR is forthcoming...
