### ISSUE TITLE
Authentication Failure - Internal Server error

### ISSUE THREAD

**Issue by ajnasaboobacker** [alandtse/alexa_media_player#2202] opened 2024-03-04 01:32 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Alexa Media player configuration failed, after entering the captcha. The sits redirects to and give me a Internal Server error.

**To Reproduce**

Download the Alexa Media Player repository from HACS
From Integration, select Alexa Media Player
Fill in the credentials and click submit
The browser page should be pop up,  enter the credentials and click login
on the next screen, enter the captcha and click submit

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version): 2024.3.0b5
- alexa_media (version from `const.py` or HA startup):  4.9.2
- alexapy (version from `pip show alexapy` or HA startup): 
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : Yes

**Logs**
Please provide [logs] (https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

TypeError: unsupported operand type(s) for -: 'str' and 'int'
2024-03-04 06:51:41.598 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-03-04 06:51:50.320 ERROR (Bot:5883655807:updater) [telegram.ext.updater] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-03-04 06:51:50.337 ERROR (Bot:5883655807:dispatcher) [homeassistant.components.telegram_bot.polling] Update "None" caused error: "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2024-03-04 06:51:56.248 ERROR (Bot:5883655807:updater) [telegram.ext.updater] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-03-04 06:51:56.250 ERROR (Bot:5883655807:dispatcher) [homeassistant.components.telegram_bot.polling] Update "None" caused error: "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2024-03-04 06:52:03.564 ERROR (Bot:5883655807:updater) [telegram.ext.updater] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-03-04 06:52:03.570 ERROR (Bot:5883655807:dispatcher) [homeassistant.components.telegram_bot.polling] Update "None" caused error: "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2024-03-04 06:52:09.558 ERROR (Bot:5883655807:updater) [telegram.ext.updater] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-03-04 06:52:09.561 ERROR (Bot:5883655807:dispatcher) [homeassistant.components.telegram_bot.polling] Update "None" caused error: "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2024-03-04 06:52:09.685 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'alexa_media' accesses hass.components.cloud. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from cloud directly at custom_components/alexa_media/config_flow.py, line 141: hass_url: str = get_url(self.hass, prefer_external=True), please create a bug report at https://github.com/alandtse/alexa_media_player/issues
2024-03-04 06:52:18.368 ERROR (Bot:5883655807:updater) [telegram.ext.updater] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-03-04 06:52:18.372 ERROR (Bot:5883655807:dispatcher) [homeassistant.components.telegram_bot.polling] Update "None" caused error: "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2024-03-04 06:52:31.385 ERROR (Bot:5883655807:updater) [telegram.ext.updater] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-03-04 06:52:31.388 ERROR (Bot:5883655807:dispatcher) [homeassistant.components.telegram_bot.polling] Update "None" caused error: "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2024-03-04 06:52:38.424 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
yield
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
resp = await self._pool.handle_async_request(req)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
raise exc from None
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
response = await connection.handle_async_request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
return await self._connection.handle_async_request(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
raise exc
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
) = await self._receive_response_headers(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
event = await self._receive_event(timeout=timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
data = await self._network_stream.read(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 31, in read
with map_exceptions(exc_map):
File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
self.gen.throw(value)
File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
raise to_exc(exc) from exc
httpcore.ReadTimeout
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 25, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 68, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/alexa_media/config_flow.py", line 897, in wrapped
return await cls.handler(request, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/authcaptureproxy/auth_capture_proxy.py", line 439, in all_handler
resp = await getattr(self.session, method)(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1892, in post
return await self.request(
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
return await self.send(request, auth=auth, follow_redirects=follow_redirects)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
response = await self._send_handling_auth(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
response = await self._send_handling_redirects(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
response = await self._send_single_request(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
response = await transport.handle_async_request(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
with map_httpcore_exceptions():
File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
self.gen.throw(value)
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
raise mapped_exc(message) from exc
httpx.ReadTimeout

**Additional context**
![image](https://github.com/alandtse/alexa_media_player/assets/47502431/602a1743-bf69-49a3-9831-f7662fe98b6d)

**Comment by pollinolas** [comment] 2024-03-05 18:56
The same thing is happening to me today, any news?

**Comment by alandtse** [comment] 2024-03-06 03:50
Dupe of #2167

**Closed by alandtse** 2024-03-06 03:50 UTC
