### ISSUE TITLE
HTTP 500 error in configuaration

### ISSUE THREAD

**Issue by Benz63Amg** [alandtse/alexa_media_player#2267] opened 2024-05-19 11:30 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

**To Reproduce**

1. Go to 'integration configuartion'
2. Insert the data 'password'
4. See error http 500

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version): 2024.5
- alexa_media (version from `const.py` or HA startup): lastest
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : n

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by RyRyMason** [comment] 2024-05-24 10:28
Experiencing same issue

**Comment by bungee-boy** [comment] 2024-05-29 11:00
Same here.

**Comment by bungee-boy** [comment] 2024-05-29 11:12
https://github.com/alandtse/alexa_media_player/issues/2138#issuecomment-1853807735
This solved it for me!

**Comment by alandtse** [comment] 2024-05-30 07:50
Dupe of #2138

**Closed by alandtse** 2024-05-30 07:50 UTC
Labels: duplicate
