### ISSUE TITLE
New v4.13.3 Alexia Media released causing HA crash and reboot continuously

### ISSUE THREAD

**Issue by clanic70** [alandtse/alexa_media_player#2582] opened 2024-10-03 15:13 UTC
**Describe the bug**

After one day of troubleshooting with HA due to continuous crash/reboot after 10min, I've found out that the last Alexia Media releasing was causing this frustrating issue.

**To Reproduce**

Without this update of Alexa Media integration, the system was stable for many hours. After v4.13.3 installation, immediately HA crash and auto-reboot. 

**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version:

Core 2024.10.0
Supervisor 2024.09.1
Operating System 13.1
Frontend 20241002.2

- alexa_media version (from `const.py` or HA startup log): 
v4.13.3

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

Registratore: homeassistant.util.loop
Fonte: util/loop.py:136
Prima occorrenza: 16:50:53 (5 occorrenze)
Ultima registrazione: 16:51:03

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7ff4804499d0>, '/usr/local/lib/python3.12/site-packages/certifi/cacert.pem', None, None) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 341: AlexaLogin( (offender: /usr/local/lib/python3.12/ssl.py, line 708: context.load_verify_locations(cafile, capath, cadata)), please create a bug report at https://github.com/alandtse/alexa_media_player/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/alexa_media/__init__.py", line 341, in async_setup_entry AlexaLogin(
Detected blocking call to open with args (PosixPath('/config/.storage/alexa_media.....pickle'),) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 361: await login.login(cookies=await login.load_cookie()) (offender: /usr/local/lib/python3.12/site-packages/aiohttp/cookiejar.py, line 126: with file_path.open(mode="rb") as f:), please create a bug report at https://github.com/alandtse/alexa_media_player/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry await login.login(cookies=await login.load_cookie())
Detected blocking call to open with args ('/config/custom_components/solarman/inverter_definitions/sofar_hyd3k-6k-es.yaml',) inside the event loop by custom integration 'solarman' at custom_components/solarman/solarman.py, line 31: with open(self.path + self.lookup_file) as f: (offender: /config/custom_components/solarman/solarman.py, line 31: with open(self.path + self.lookup_file) as f:), please create a bug report at https://github.com/StephanJoubert/home_assistant_solarman/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/solarman/__init__.py", line 18, in async_setup_entry await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2155, in async_forward_entry_setups await self._async_forward_entry_setups_locked(entry, platforms) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2166, in _async_forward_entry_setups_locked await asyncio.gather( File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2168, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2248, in _async_forward_entry_setup await entry.async_setup(self.hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 131, in async_setup_entry return await hass.data[DATA_COMPONENT].async_setup_entry(entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 194, in async_setup_entry return await self._platforms[key].async_setup_entry(config_entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 328, in async_setup_entry return await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 358, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/solarman/sensor.py", line 89, in async_setup_entry _do_setup_platform(hass, entry.options, async_add_entities) File "/config/custom_components/solarman/sensor.py", line 54, in _do_setup_platform inverter = Inverter(path, inverter_sn, inverter_host, inverter_port, inverter_mb_slaveid, lookup_file) File "/config/custom_components/solarman/solarman.py", line 31, in __init__ with open(self.path + self.lookup_file) as f:
Detected blocking call to open with args (PosixPath('/config/.storage/alexa_media.cla.nic70@gmail.com.pickle'),) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 361: await login.login(cookies=await login.load_cookie()) (offender: /usr/local/lib/python3.12/site-packages/aiohttp/cookiejar.py, line 121: with file_path.open(mode="wb") as f:), please create a bug report at https://github.com/alandtse/alexa_media_player/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry await login.login(cookies=await login.load_cookie())
Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7ff47af63cd0>,) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 876: http2 = HTTP2EchoClient( (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/alandtse/alexa_media_player/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/alexa_media/__init__.py", line 363, in async_setup_entry await setup_alexa(hass, config_entry, login) File "/config/custom_components/alexa_media/__init__.py", line 1266, in setup_alexa await http2_connect() File "/config/custom_components/alexa_media/__init__.py", line 876, in http2_connect http2 = HTTP2EchoClient(

**Additional context**

**Comment by Xytho** [comment] 2024-10-03 15:21
Duplicate of #2579

**Comment by amandaworkman1988** [comment] 2024-10-03 15:21
I have this exact issue too!

**Comment by foxuio** [comment] 2024-10-03 15:25
same issue, HA. reboot continuously

**Comment by Armilar** [comment] 2024-10-03 15:27
It happens to me too. HA crashes immediately and automatically restarts. The boot loop then repeats itself permanently.

**Comment by clanic70** [comment] 2024-10-03 15:28
Better to restore a previous HA core backup and skip this Alexa update version until a fix will be found 😞

**Comment by clanic70** [comment] 2024-10-03 15:35
> Duplicate of #2579 

Yes you're right, I saw now the same topic. 👍

**Comment by ellsa100** [comment] 2024-10-03 15:49
same for me. had to restore previous full backup

**Comment by fuzzysb** [comment] 2024-10-03 16:18
Same for Me also, downgraded plugin, took me a while, fell victim to new HA core update, alexa Media player update and firmware update for my zigbee stick..... scratching my head as to the cause.

**Comment by Vetscarehome** [comment] 2024-10-03 16:19
I have the exact same problem, multiple reboots. I disabled the integration and the problem was solved.

**Comment by Scope666** [comment] 2024-10-03 16:22
Everyone that's run into this, does v4.13.2 definitely solve it?  I got bit by this after upgrading this morning, but I've also had a similar issue a couple days ago, and I'm wondering if v4.13.2 can still cause it after it's been running for awhile.

**Comment by ingo916** [comment] 2024-10-03 16:23
I am having the same issue, I had to disable the Alexa Media Player integration. works fine now. I'll have to wait for the next update.

**Comment by robikop** [comment] 2024-10-03 16:36
Same here. I reverted to the previous version…

**Comment by cliviu74** [comment] 2024-10-03 17:06
Could be related to the storing the cookie in the pickle file

` WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args (PosixPath('/config/.storage/alexa_media.amazon@email.tld.pickle'),) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 361`

> 2024-10-03 17:48:31.071 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args (PosixPath('/config/.storage/alexa_media.amazon@email.tld.pickle'),) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 361: await login.login(cookies=await login.load_cookie()) (offender: /usr/local/lib/python3.12/site-packages/aiohttp/cookiejar.py, line 126: with file_path.open(mode="rb") as f:), please create a bug report at https://github.com/alandtse/alexa_media_player/issues

For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open

`

**Comment by cliviu74** [comment] 2024-10-03 17:15
@alandtse this release needs to be pulled back until it's fixed. The home assistant crash is pretty nasty

**Comment by rikmueller** [comment] 2024-10-03 17:17
Went back to previous version (re-downloaded it via hacs). Pretty bad bug.

**Comment by clanic70** [comment] 2024-10-03 18:24
> @clanic70 you  have leaked your email address in the log. You might want to edit your original post and anonimize it in the log sample (search for .pickle)

Thanks for warning me! I didn't check the log deeply 😞

**Comment by upholland** [comment] 2024-10-03 20:15
Facing the same problem, HA keeps crashing when updated Alexa media player to version 14.13.3

**Comment by Jojo-A** [comment] 2024-10-03 20:18
@clanic70 Please close this issue because it is a duplicate of #2579 

EVERYONE:
check out #2579 

Where is the point in opening one after another issue regarding the same problem?!

**Comment by clanic70** [comment] 2024-10-03 20:53
Calm down! The point was; no clear problem statement in the title. Now I know we are talking about the same issue.
No problem to close it 😉

**Comment by Jojo-A** [comment] 2024-10-03 20:54
Thank you!

**Closed** 2024-10-03 20:54 UTC

**Comment by CancunManny** [comment] 2024-10-03 23:53
> Everyone that's run into this, does v4.13.2 definitely solve it? I got bit by this after upgrading this morning, but I've also had a similar issue a couple days ago, and I'm wondering if v4.13.2 can still cause it after it's been running for awhile.

Yes, v4.13.2 is stable, at least for me.

**Comment by foxuio** [comment] 2024-10-04 00:15
Only restart HA system  and quickly disable temporarily the plugin Alexa
media... Until fix this. Is not necessary restore from full backup

**Comment by Scope666** [comment] 2024-10-04 02:10
A couple days ago, before v4.13.3 I ran into this where the CPU was pegged by HA, and even rebooting didn't fix it.  Restoring from backup did ... maybe it's a different issue ... db corruption or something.  Regardless it's similar to what's mentioned in this issue, and that did happen to me this morning before I found this post.

**Comment by PJLLB** [comment] 2024-10-04 06:52
It appears they have pulled 4.13.3.
