### ISSUE TITLE
404 error when setting up alexa intergration

### ISSUE THREAD

**Issue by f3bandit** [alandtse/alexa_media_player#2318] opened 2024-07-15 22:16 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
404 error when setting up alexa intergration

404 error when setting up alexa intergration under services and devices. get a 404 error after clicking open website during final step of setup process.
**To Reproduce**

**Expected behavior**

alexa integration to work
**Screenshots**

**System details**

- Home-assistant (version):
- Core 2024.7.2
- Supervisor 2024.06.2
- Operating System 12.4
- Frontend 20240710.0
- alexa_media (version from `const.py` or HA startup):
- v4.10.3
- alexapy (version from `pip show alexapy` or HA startup):
- idk
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :
YES
**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by danielbrunt57** [comment] 2024-07-16 20:46
Please try adding custom repository [https://github.com/danielbrunt57/alexa_media_player](https://github.com/danielbrunt57/alexa_media_player), install latest version (4.10.3.1) and report results.

**Comment by f3bandit** [comment] 2024-07-16 20:58
> Please try adding custom repository https://github.com/danielbrunt57/alexa_media_player, install latest version (4.10.3.1) and report results.

nope 404 error

**Comment by f3bandit** [comment] 2024-07-16 21:14
idk if any of this is useful
logs:
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 5:06:37 PM (4 occurrences)
Last logged: 5:06:44 PM

Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/frontend", "/config/custom_components/hacs/hacs_frontend", False)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 54: hass.http.register_static_path(f"{URL_BASE}/frontend", locate_dir(), cache_headers=False), please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 57: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by danielbrunt57** [comment] 2024-07-17 05:46
@f3bandit 
The recommended `await hass.http.async_register_static_paths(...` is already implemented in my current 4.10.3.1 release.
alantse's 4.10.3 dev branch has the new code as well but they've not published a new release with it yet.

And no, it's not relevant to this issue as those message are only alerts and do not prevent the old code from working.  When HA 20**_25_**.7 comes out, the `hass.http.async_register_static_paths()` will cease to exist and the code will fail completely.  But that's still a year away.
```
Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/frontend", "/config/custom_components/hacs/hacs_frontend", False)]); This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 54: hass.http.register_static_path(f"{URL_BASE}/frontend", locate_dir(), cache_headers=False), please create a bug report at https://github.com/hacs/integration/issues
```
```
Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)]); This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 57: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
```
![image](https://github.com/user-attachments/assets/96d770a1-066b-4328-b051-5c6d69d94f72)

![image](https://github.com/user-attachments/assets/5d809786-b783-4087-a51b-ebd892650272)

**Comment by danielbrunt57** [comment] 2024-07-17 05:59
> 404 error when setting up alexa intergration under **_services and devices_**.

You mean Devices & Services > Integrations!
My initial config entry configuration looks like this:

![image](https://github.com/user-attachments/assets/a75e5596-4b8e-4121-95a7-2b52b08f2025)

Please post a screenshot of the one you are seeing and which fields you are completing.

**Comment by f3bandit** [comment] 2024-07-17 06:07
![image](https://github.com/user-attachments/assets/06f5d647-0f62-435c-bd23-4a4cafffd3b6)

**Comment by danielbrunt57** [comment] 2024-07-17 06:08
Which fields are you filling in?

**Comment by f3bandit** [comment] 2024-07-17 06:31
email, password. built-in 2FA key, public url.

**Comment by danielbrunt57** [comment] 2024-07-17 07:07
Please post a screenshot of what you see after you `SUBMIT`

**Comment by f3bandit** [comment] 2024-07-17 09:24
![image](https://github.com/user-attachments/assets/479ef852-052f-4fea-974f-95733ea25305)

**Comment by f3bandit** [comment] 2024-07-17 09:27
![image](https://github.com/user-attachments/assets/d2743cc6-2f7a-46bf-b593-8a2826e5cc78)

**Comment by f3bandit** [comment] 2024-07-17 09:28
![image](https://github.com/user-attachments/assets/f4a35733-093d-48a0-be01-cdef2c8723c7)

**Comment by f3bandit** [comment] 2024-07-17 09:28
![image](https://github.com/user-attachments/assets/d8bf7e61-38aa-45e2-8e1c-662119709cdd)

**Comment by danielbrunt57** [comment] 2024-07-17 12:17
Are you entering your public URL as 
`https://my_unique_id.ui.nabucasa/` (with training slash)
or as
`https://my_unique_id.ui.nabucasa` (without trailing slash)?

**Comment by f3bandit** [comment] 2024-07-17 12:46
with

**Comment by f3bandit** [comment] 2024-07-17 13:11
I have even tried my local address and still get a 404

**Comment by danielbrunt57** [comment] 2024-07-17 13:25
Could you please retry your external nabu casa URL but without the trailing slash?
I've been adding mine without the trailing slash and it succeeds.
I just tried now with the slash and it still worked but I'm using my own public URL and not nabu casa.
The URL I'm sent to is
`https://<my_external_url>/auth/alexamedia/proxy?config_flow_id=01J30DHW4KNFFW1AAQ4FCAVM6G&callback_url=https://<my_public_url>/auth/alexamedia/callback?flow_id%3D01J30DHW4KNFFW1AAQ4FCAVM6G`

**Comment by f3bandit** [comment] 2024-07-17 20:56
![image](https://github.com/user-attachments/assets/e0dda316-7801-4fb7-8a8b-67b45bd5bbcb)
![image](https://github.com/user-attachments/assets/069af498-6f89-4265-b4b3-64cd362c88db)
![image](https://github.com/user-attachments/assets/cc4c16fe-e949-4075-8aad-75573b31b4b1)
![image](https://github.com/user-attachments/assets/d59f0d93-afc2-47ed-9005-553ea571b879)

**Comment by danielbrunt57** [comment] 2024-07-17 21:12
What is the URL of this page?

![image](https://github.com/user-attachments/assets/e83ac8f1-1991-4353-8495-a5ef0d5daabc)

**Comment by f3bandit** [comment] 2024-07-17 21:29
https://<my_public_ha_address>/auth/alexamedia/proxy?config_flow_id=01J317CKVVMKCBK6APXZB04E02&callback_url=https://og45bkm95tbj4hz03t2yoiuxyevv6gir.ui.nabu.casa/auth/alexamedia/callback?flow_id%3D01J317CKVVMKCBK6APXZB04E02

**Comment by danielbrunt57** [comment] 2024-07-17 21:45
and just to confirm, the <my_public_address> in your reply is `https://<redacted>.ui.nabu.casa`?

**Comment by f3bandit** [comment] 2024-07-17 22:04
> and just to confirm, the <my_public_address> in your reply is `https://<redacted>.ui.nabu.casa`?

correct  sir

**Comment by danielbrunt57** [comment] 2024-07-18 05:01
I'm at a loss as to why nabu casa is rejecting the callback.  Has this integration functioned previously with nabu casa?

**Comment by f3bandit** [comment] 2024-07-18 05:13
yes when I used it back on the raspberry pie 4 that I had running home assistant. but we had a lightening strike that took out alot of stuff. so I upgraded it to a Home assistant yellow. idk if this matters or not, but idk if you are in the USA or not but i am. and you cannot access alexa.amazon.com anymore without scanning a QR code and using the alexa app.

**Comment by danielbrunt57** [comment] 2024-07-18 07:52
I am in Canada and can use amazon.ca or amazon.com with my same account credentials (both require a 2FA TOTP code).  
My echos are still in my amazon.com account and therefore use amazon.com.
I also setup the Alexa skill (since I don't use Nabu Casa) in amazon.com, but that aspect is unrelated to Alexa Media Player.

**Comment by danielbrunt57** [comment] 2024-07-18 08:12
I've posted this topic in the community...

https://community.home-assistant.io/t/is-there-anyone-successfully-using-alexa-media-player-integration-in-conjunction-with-nabu-casa-for-their-public-url/750890

**Comment by danielbrunt57** [comment] 2024-07-18 20:38
There's been no useful replies on my topic yet so I went ahead and resubscribed to Nabu Casa Cloud, re-activated the HA `cloud:
`component I had commented out, restarted HA and nabu casa is now active for me.

![image](https://github.com/user-attachments/assets/733df1e7-2997-48ef-aff6-36aad1d7c395)

I deleted my AMP integration, re-added it and my comfig setup completed successfully 

![image](https://github.com/user-attachments/assets/7cffaca6-100f-4859-802a-346536bf6df6)

So, there's no issues in the Alexa Media Player integration or Nabu Casa cloud.
Something else is wrong/not working in your setup.

Can you log into your system remotely?

![image](https://github.com/user-attachments/assets/ec52f0b7-4c69-4cd9-863d-0f8508013388)

**Comment by f3bandit** [comment] 2024-07-18 21:09
yes

![image](https://github.com/user-attachments/assets/b581afe8-e911-4e9b-8af9-e5ea67e67584)

**Comment by f3bandit** [comment] 2024-07-18 21:13
I can even disconnect my phone from wifi and connect to it without issue
![image](https://github.com/user-attachments/assets/6e5e6194-1715-4d29-a540-aa449a3d5c45)

**Comment by f3bandit** [comment] 2024-07-18 21:22
idk what could be wrong tbh everything is pretty stock other than HACS being installed 
you are welcome to connect to my system and check stuff out if that helps!?!

**Comment by f3bandit** [comment] 2024-07-18 23:12
Just did a fresh install of home assistant on the HA Yellow box. I still get a 404 error

**Comment by f3bandit** [comment] 2024-07-18 23:23
seems to me the file is not being created
![image](https://github.com/user-attachments/assets/d49f2233-c41b-4308-ae00-eac3e352c8f3)

**Comment by f3bandit** [comment] 2024-07-18 23:28
just found this in the logs

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:135
integration: HTTP ([documentation](https://www.home-assistant.io/integrations/http), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+http%22))
First occurred: 7:15:45 PM (1 occurrences)
Last logged: 7:15:45 PM

Login attempt or request with invalid authentication from 200.200.200.38 (200.200.200.38). Requested URL: '/auth/alexamedia/proxy?config_flow_id=3D01J341NHP9SWMGV0988WY4RWZJ&callback_url=http://200.200.200.4:8123/auth/alexamedia/callback?flow_id%3D01J341NHP9SWMGV0988WY4RWZJ'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36)

**Comment by danielbrunt57** [comment] 2024-07-18 23:39
What subnet is your public IP?  (in Google, search for "what is my ip address"

Once http.ban is triggered, it may block the ip, at which point  you have to edit config/ip_bans.yaml to remove the entry.  that or just delete the file, and restart of course.

**Comment by f3bandit** [comment] 2024-07-19 00:21
64.72.51.222   not seeing a config/ip_bans.yaml

**Comment by danielbrunt57** [comment] 2024-07-19 00:53
I have no idea where 200.200.200.83 is coming from then...

**Comment by f3bandit** [comment] 2024-07-19 01:07
> I have no idea where 200.200.200.83 is coming from then...

it's my desktops IP on the network

**Comment by danielbrunt57** [comment] 2024-07-19 01:30
You'll need to sort through getting the HA Yellow box setup properly with remote access working via the nabu casa external URL...

**Comment by f3bandit** [comment] 2024-07-19 01:55
weird
![image](https://github.com/user-attachments/assets/fbb8a01f-fc13-4687-8f26-2a742398c019)

**Comment by f3bandit** [comment] 2024-07-19 02:00
fixed buit still get a 404 error

**Comment by danielbrunt57** [comment] 2024-07-19 02:18
Ok, so that post you made with "weird" and the image.png at 6:56 pm PDT and then deleted?  well, I got email notification of the post and the png where you obfuscated most of your nabu casa URL's, except one.  Anyways, I typed it character by character and I got your HA login screen (not that I can do anything with it without your user name & password!) but it proves to me the URL works externally.  Now why are AMP & Nabu not happy with each other when they are on my system...  I can feel another sleepless night coming on as these unsolved mysteries tend to keep me up all night!

**Comment by danielbrunt57** [comment] 2024-07-19 02:27
Okay, so I googled this: 404 not found ui.nabu.casa/ap/cvf/approval
And that led me to this : https://github.com/alandtse/alexa_media_player/issues/1725
And I believe this is your issue.  Aloso confirmed by looking again at your screeshots sbove where I see you are NOT getting to the Amazon TOTP screen!

![image](https://github.com/user-attachments/assets/70bdd7d6-3640-452f-b832-74b16682962c)

You appear to have app approval enabled on your amazon account, not OTP!

**Comment by f3bandit** [comment] 2024-07-19 02:32
not sure what you mean there 
![image](https://github.com/user-attachments/assets/bfd2e920-b12c-4299-8692-17c51c2885b6)
this is what I have been using, is this wrong?

**Comment by danielbrunt57** [comment] 2024-07-19 02:42
![image](https://github.com/user-attachments/assets/a1baa14e-7ce7-418c-a617-e8b314ab5fc6)

It's kinda convoluted & confusing the way they've set 2SV up and it confuses the hell out of me, but then again, it's Amazon!.  I would try clearing you 2SV settings and try setting them up again.  I really can't see where you could disable the "app approval" that you are being directed to rather than OTP.

![image](https://github.com/user-attachments/assets/01f316af-8c4c-425b-816e-21d14233abc9)

**Comment by f3bandit** [comment] 2024-07-19 02:47
![image](https://github.com/user-attachments/assets/5e440d40-aa4a-43cf-9a60-c8133766fd54)

**Comment by f3bandit** [comment] 2024-07-19 03:02
still get a 404

**Comment by danielbrunt57** [comment] 2024-07-19 03:08
Did you disable and re-enable 2SV?

**Comment by danielbrunt57** [comment] 2024-07-19 03:13
![image](https://github.com/user-attachments/assets/027380fa-60c3-49dd-a71e-0542db3415c3)

**Comment by f3bandit** [comment] 2024-07-19 03:23
yes still 404

**Comment by f3bandit** [comment] 2024-07-19 03:34
cleared my settings and apps and made sure app otp was the primary

**Comment by f3bandit** [comment] 2024-07-19 05:24
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:135
integration: HTTP ([documentation](https://www.home-assistant.io/integrations/http), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+http%22))
First occurred: July 18, 2024 at 9:58:01 PM (5 occurrences)
Last logged: July 18, 2024 at 9:58:04 PM

Login attempt or request with invalid authentication from localhost (127.0.0.1). Requested URL: '/auth/token'. (Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36)
Login attempt or request with invalid authentication from localhost (127.0.0.1). Requested URL: '/auth/token'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36)

**Comment by danielbrunt57** [comment] 2024-07-19 08:17
![image](https://github.com/user-attachments/assets/f61ced63-99c4-454e-9aed-7621461218ab)

**Comment by f3bandit** [comment] 2024-07-19 08:40
apparently there was a lock on my account as amazon believed someone was trying to hack my account
I'm waiting for them to get it removed. I created a test amazon acount and everything worked perfect

**Comment by danielbrunt57** [comment] 2024-07-23 16:18
These are all HACS warninigs and have nothing to do with AMP.
> Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/frontend", "/config/custom_components/hacs/hacs_frontend", False)]); This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 54: hass.http.register_static_path(f"{URL_BASE}/frontend", locate_dir(), cache_headers=False), please create a bug report at https://github.com/hacs/integration/issues
> Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)]); This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 57: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
> Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
> Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

@alantse Please close this

**Comment by danielbrunt57** [comment] 2024-07-25 03:37
@alandtse I believe this can now be closed...

**Closed** 2024-07-25 04:16 UTC
