### ISSUE TITLE
An error occurred accessing AlexaAPI: `LoginError occurred. Arguments: ('Unauthorized',)`

### ISSUE THREAD

**Issue by micium** [alandtse/alexa_media_player#2429] opened 2024-08-08 12:34 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

all amazon devices are available but I can't use them

**To Reproduce**

updated to 2024.8.0 and fix manifest.json with "alexapy==1.28.2"

**Expected behavior**

notify (TTS) to alexa devices but not working with errors 

**Screenshots**

Registratore: alexapy.helpers
Fonte: runner.py:190
Prima occorrenza: 12:53:26 (3 occorrenze)
Ultima registrazione: 12:53:26

alexaapi.run_behavior((<alexapy.alexaapi.AlexaAPI object at 0x7f69d69190>, {'@type': 'com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode', 'type': 'Alexa.Speak', 'operationPayload': {'deviceType': 'A3VRME03NAXFUB', 'deviceSerialNumber': 'G316', 'locale': 'it-it', 'customerId': 'AG0W', 'textToSpeak': 'ciao', 'target': {'customerId': 'AG0W', 'devices': [{'deviceSerialNumber': 'G316', 'deviceTypeId': 'A3VRME03NAXFUB'}]}, 'skillId': 'amzn1.ask.1p.saysomething'}}), {'queue_delay': 1.5}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Unauthorized',)
alexaapi.send_sequence((<alexapy.alexaapi.AlexaAPI object at 0x7f69d69190>, 'Alexa.Speak'), {'customer_id': 'A292ZASRY7G0W', 'textToSpeak': 'ciao', 'target': {'customerId': 'AG0W', 'devices': [{'deviceSerialNumber': 'G*********316', 'deviceTypeId': 'A3VRME03NAXFUB'}]}, 'skillId': 'amzn1.ask.1p.saysomething', 'queue_delay': 1.5}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Unauthorized',)
alexaapi.send_tts((<alexapy.alexaapi.AlexaAPI object at 0x7f69d69190>, 'ciao'), {'customer_id': 'A292ZASRY7G0W', 'queue_delay': 1.5}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Unauthorized',)

**System details**

- Home-assistant (version): 2024.8.0
- alexa_media (version from `const.py` or HA startup): v4.12.6 + fix manifest.json with "requirements": ["alexapy>=1.28.2", "packaging>=20.3", "wrapt>=1.14.0"],
- alexapy (version from `pip show alexapy` or HA startup): 1.28.2
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :  YES

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by meluvalli** [comment] 2024-08-08 15:54
I also have this problem.  It is completely broken now.

**Comment by chrisvblemos** [comment] 2024-08-08 18:41
Can you try again with the new release 4.12.7?

**Comment by micium** [comment] 2024-08-08 19:39
same problem also with new releaee 4.12.7

**Comment by r0bb10** [comment] 2024-08-09 06:57
> Can you try again with the new release 4.12.7?

works again for me on 4.12.7!

**Comment by cibernox** [comment] 2024-08-09 11:57
Same here. Updating to the latest release fixed it.

**Comment by micium** [comment] 2024-08-09 21:45
I did various tests based also on the other open issues, unfortunately the problem seemed solved after reauthentication (deleted integration and reconfigured from scratch) but after about a couple of hours it reappeared.
My configuration was HA 2024.8.0, AMP 4.12.7, I'm writing this because I rool back to HA 2024.7.4 again and everything works fine

**Comment by alandtse** [comment] 2024-08-21 01:39
@danielbrunt57 there are many dupe issues to track with the same root cause `LoginError occurred. Arguments: ('Unauthorized',)`. It makes it harder for both users and devs to actually track the issue. I'd suggest that you mark them as dupes of each other and then choose one (with the best info) as the main one you update while closing all others.

Also, when you submit a PR, you can identify which issues it'll close so it auto cleans up when its merged but also lets people know there's a PR that may close the issue.

**Comment by danielbrunt57** [comment] 2024-08-21 07:18
> @danielbrunt57 there are many dupe issues to track with the same root cause `LoginError occurred. Arguments: ('Unauthorized',)`. It makes it harder for both users and devs to actually track the issue. 

Yes, I'm aware of that and realize it's kinda out of hand, hence why I went through them and edited the title with the initial, most relevant `error message` to make the next step (your recommendation) easier.

> I'd suggest that you mark them as dupes of each other and then choose one (with the best info) as the main one you update while closing all others.

I will, when my spare time permits.
I have to get my house ready to list as early in September as I can manage and I have a LOT to do.  I'm currently in a financial crisis...

> Also, when you submit a PR, you can identify which issues it'll close so it auto cleans up when its merged but also lets people know there's a PR that may close the issue.

I try!

**Closed** 2024-10-31 05:38 UTC
