### ISSUE TITLE
Failed to login using.com.au

### ISSUE THREAD

**Issue by sambarlick** [alandtse/alexa_media_player#2427] opened 2024-08-08 10:35 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
Unable to login in using amazon.com.au when adding integration. The authorisation callback completes successfully but then HA gives an error when returning to HA saying failed to login. I tested logging with amazon.com and it successfully logged in, but as my devices are associated with a .com.au account they don't appear.
I'm on AMP version 4.12.6 and HA.2024.8.0

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20240808-201814](https://github.com/user-attachments/assets/79cdc6c8-080e-4017-9b04-d5b936654232)

**System details**

- Home-assistant (version): 2024.8.0
- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y). : yes

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by elax46** [comment] 2024-08-08 10:41
I join the request because after the last update I too am having the exact same problem

**Comment by joust1** [comment] 2024-08-08 10:49
I join the request because after the last update I too am having the same problem for a co.uk account.

**Comment by ChristophCaina** [comment] 2024-08-08 10:55
duplicate of #2407 
fix in pr #2423 

workaround:
open `/custom_components/alexa_media_player/manifest.json`
change the version for `alexapy` to `1.28.2`

**Comment by Turbovix** [comment] 2024-08-08 11:12
Hello developer, the same problem here. After this last update, authentication is successful, but soon after HA asks to reconfigure and stays in this loop.

**Comment by BWE83** [comment] 2024-08-08 11:31
The following workaround works for amazon.de:
open /custom_components/alexa_media_player/manifest.json
change the version for alexapy to 1.28.2

**Comment by klingon888** [comment] 2024-08-08 12:22
amazon.us. Changing version to 1.28.2 not working for me. Getting error "Failed to setup" in the integration's page. Rebooting HASS not fixing issue either.

**Comment by alxhander** [comment] 2024-08-08 12:42
I join the request because after the last update I too am having the same problem for a com.br account.

- Home-assistant: 2024.8.0
- alexa_media: 4.12.6

**Comment by oe1gxk** [comment] 2024-08-08 12:42
Works not with amazon.de and alexapy==1.28.2 HAS 2024.8.0 amp 4.12.6

**Comment by richsimpson** [comment] 2024-08-08 13:08
.co.uk here and 2024.8 Home Assistant Core

The change mentioned to the custom_component file (change Alexapy to 1.28.2

Working fine, but had to do it twice as left it as .com to begin.

**Comment by danielbrunt57** [comment] 2024-08-08 13:25
People may need [PR#2423](https://github.com/alandtse/alexa_media_player/pull/2423) to be merged.
It addresses .de and other domains...

**Comment by alxhander** [comment] 2024-08-08 15:20
> I join the request because after the last update I too am having the same problem for a com.br account.
> 
> * Home-assistant: 2024.8.0
> * alexa_media: 4.12.6

The following workaround works for amazon.br:
open /custom_components/alexa_media_player/manifest.json
change the version for alexapy to 1.28.2

**Comment by elax46** [comment] 2024-08-08 16:26
> > I join the request because after the last update I too am having the same problem for a com.br account.
> > 
> > * Home-assistant: 2024.8.0
> > * alexa_media: 4.12.6
> 
> The following workaround works for amazon.br: open /custom_components/alexa_media_player/manifest.json change the version for alexapy to 1.28.2

This solution also works for my instance

**Comment by garrathbond** [comment] 2024-08-08 17:27
i also have had to use this work around!!

**Comment by tecnobrat** [comment] 2024-08-08 17:36
Working for me now after upgrading to 4.12.7 and I use `amazon.ca`.

I still have the ongoing [cookie partition issue](https://github.com/alandtse/alexa_media_player/issues/2288), but thats unrelated to this. Reloading the integration after startup workaround still works for that.

**Closed** 2024-08-08 18:16 UTC
