### ISSUE TITLE
Integration stop working after some time: `Login error detected; not contacting API`

### ISSUE THREAD

**Issue by antoweb** [alandtse/alexa_media_player#2448] opened 2024-08-09 13:24 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

WHen i use media_player alexa wont work, the integration must be reloaded for retunr to working

**To Reproduce**

1. Run an action for alexa media player (tts)
2. Alexa wont talk

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version): 2024.8.0
- alexa_media (version from `const.py` or HA startup):4.12.7
- alexapy (version from `pip show alexapy` or HA startup):4.12.7
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**

Logs

2024-08-09 15:18:43.563 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 960, in send_announcement
await self.send_sequence(
File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 512, in send_sequence
await self.run_behavior(node_data, queue_delay=queue_delay)
File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 434, in run_behavior
await self._post_request("/api/behaviors/preview", data=data)
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 226, in _post_request
return await self._request("post", uri, data, query)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
ret = await target(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 199, in _request
raise AlexapyLoginError("Login error detected; not contacting API")
alexapy.errors.AlexapyLoginError: Login error detected; not contacting API
2024-08-09 15:18:55.761 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 960, in send_announcement
await self.send_sequence(
File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 512, in send_sequence
await self.run_behavior(node_data, queue_delay=queue_delay)
File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 434, in run_behavior
await self._post_request("/api/behaviors/preview", data=data)
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 226, in _post_request
return await self._request("post", uri, data, query)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
ret = await target(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 199, in _request
raise AlexapyLoginError("Login error detected; not contacting API")
alexapy.errors.AlexapyLoginError: Login error detected; not contacting API
2024-08-09 15:18:59.798 ERROR (MainThread) 
Additional context

**Comment by antoweb** [comment] 2024-08-09 13:29
same issue as https://github.com/alandtse/alexa_media_player/issues/2442

**Comment by ob1w4nken0b1** [comment] 2024-08-09 20:34
+1 on this

**Comment by rymiller11** [comment] 2024-08-09 21:27
+1 on this

**Comment by javilopezalarcon** [comment] 2024-08-10 13:29
+1

**Comment by jleinenbach** [comment] 2024-08-10 16:14
As I don't have this issue: Have you already tried to:
- remove the integration
- delete the config/.storage/alexa_media.[email-address].pickle file
- install and configure the integration again?

**Comment by antoweb** [comment] 2024-08-10 16:23
> As I don't have this issue: Have you already tried to:
> 
> * remove the integration
> * delete the config/.storage/alexa_media.[email-address].pickle file
> * install and configure the integration again?

Yes nothing changed

**Comment by chrisvblemos** [comment] 2024-08-10 16:48
@antoweb , few questions...

Domain?
Using 2FA with external authenticator app?
Using external Home Assistant URL?
Can you check logs for any HTTP2 mentions related to AMP?

**Comment by antoweb** [comment] 2024-08-10 17:08
Issue Is common in Europe see other issue already opened mentioned above
Anyways:
2fa with permanente token
External url public
Log are above

**Comment by jleinenbach** [comment] 2024-08-10 20:37
I'm in Europe (amazon.de) and don't have these issues.
> alexapy (version from pip show alexapy or HA startup):4.12.7
This should should be v1.28.2

Your logs do not include the issue, the errors are just a result of it.
You should reboot, activate the debuglogs, reload the integration, wait until it fails, then save the logs.

**Comment by javilopezalarcon** [comment] 2024-08-10 21:01
I'm amazon.es and i have these problems

**Comment by gutisoft2** [comment] 2024-08-11 07:21
Yo soy Amazon.es y también tengo ese problema. Las automatizaciones funcionan perfectamente, pero no anuncia nada Alexa.
Probe en desinstalar Alexa media, reiniciar, elimiar el archivo del config y nada de nada.
De momento la única solución temporal, reiniciar Alexa cada 10 minutos.

**Comment by zibous** [comment] 2024-08-11 08:29
> I'm in Europe (amazon.de) and don't have these issues.

Same here:

AlexaPy Version: 1.28.2
alexa_media: "4.12.7"
homeassistant: 2024.8.1 Dockerversion

1. Reinstall alexa_media player 
2. Register ad amazon.de all devices work perfectly 
3. --> No Error ! 
4. restart Homeassistant 
5. --> Error http.cookies.CookieError: Invalid attribute 'partitioned'


```log
2024-08-11 07:21:44.774 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry *****@***.com - amazon.de for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 359, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 328, in load_cookie
    cookies = pickle.loads(await myfile.read())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/cookies.py", line 312, in __setitem__
    raise CookieError("Invalid attribute %r" % (K,))
http.cookies.CookieError: Invalid attribute 'partitioned'
```

Current workaround:

```yaml
- id: reload_alexa_on_start
      alias: Reload Alexa Media Player after HA starts
      description: "Behebt den Fehler, damit alle Alexa Media Player nach dem Start wiedelr laufen...."
      initial_state: true
      trigger:
        - platform: homeassistant
          event: start
      condition: []
      action:
        - delay:
            hours: 0
            minutes: 1
            seconds: 0
            milliseconds: 0
        - alias: Reload Alexa Media Player integration
          service: homeassistant.reload_config_entry
          data: {}
          target:
            entity_id:
              - "media_player.alexa1" #single echo device
              - "media_player.alexa2" #single echo device
              - "media_player.alexa3" #single echo device
              - "media_player.alexa4" #single echo device
              - "media_player.alexa5" #single echo device
              - "media_player.alexa6" #single echo device
```

sorry, stressful and it's a shame that it doesn't work anymore.

**Comment by rewri3** [comment] 2024-08-11 10:15
I had the same problem and I'm following the thread waiting for a solution. But I've found that if I set AMP > three dots > system options > enable new entity additions and enable polling for updates to off, the integration doesn't stop working. It's been running for 4 hours now. I hope it can be useful.

**Comment by zibous** [comment] 2024-08-11 14:26
> I set AMP > three dots > system options > enable new entity additions and enable polling for updates to off,

Negatov, do not work for me.

But test inside the docker homeassistant:

```
python -m pickle alexa_media.***.***@gmail.com.pickle

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/pickle.py", line 1815, in <module>
    obj = load(f)
          ^^^^^^^
  File "/usr/local/lib/python3.12/http/cookies.py", line 312, in __setitem__
    raise CookieError("Invalid attribute %r" % (K,))
http.cookies.CookieError: Invalid attribute 'partitioned'
```

Delete alexa_media.***.***@gmail.com.pickle and renew shows the same error.

**Comment by josemaX** [comment] 2024-08-11 16:46
Home-assistant (version): 2024.8.0
alexa_media (version):4.12.7

After reconfiguring the integration as commented in other issue, restarting the computer (no home assistant), Alexa plays the HA messages in automations for a bunch of minutes, after that, no speaking again.

Then if I reload the AMP integration, works again for a while, and fails after a while until reload the integration and so on.

**Comment by andrea-git** [comment] 2024-08-11 16:49
> I had the same problem and I'm following the thread waiting for a solution. But I've found that if I set AMP > three dots > system options > enable new entity additions and enable polling for updates to off, the integration doesn't stop working. It's been running for 4 hours now. I hope it can be useful.

After this settings the devices continue to play and speaking since 2 hours, The temperatures are still unavailable

**Comment by gutisoft2** [comment] 2024-08-11 17:01
> I had the same problem and I'm following the thread waiting for a solution. But I've found that if I set AMP > three dots > system options > enable new entity additions and enable polling for updates to off, the integration doesn't stop working. It's been running for 4 hours now. I hope it can be useful.

This work for me now. It's been running for 6 hours now

**Comment by ob1w4nken0b1** [comment] 2024-08-11 17:22
> I had the same problem and I'm following the thread waiting for a solution. But I've found that if I set AMP > three dots > system options > enable new entity additions and enable polling for updates to off, the integration doesn't stop working. It's been running for 4 hours now. I hope it can be useful.

Thanks!! This fix is working for me...about 6 hours of notifications

**Comment by antoweb** [comment] 2024-08-11 18:01
Ok but without polling the alarms and other services of amo Will be update d?

**Comment by rewri3** [comment] 2024-08-11 18:54
No without polling communication with Alexa is one-way. I realized that the problem is not solved, but if you only use notifications via Alexa it's better than nothing...

**Comment by darioz90** [comment] 2024-08-11 19:36
same problem later a few minutes the entity stops working for no reason, when reloaded it starts working again for a few minutes
![IMG_4896](https://github.com/user-attachments/assets/b1e6840b-3535-4c90-830b-1718a049e229)

**Comment by darioz90** [comment] 2024-08-11 19:43
How i can fix?

**Comment by andrea-git** [comment] 2024-08-11 20:27
> No without polling communication with Alexa is one-way. I realized that the problem is not solved, but if you only use notifications via Alexa it's better than nothing...


Yes, but meanwhile that the problem will be fixed, is a valid workaround

**Comment by antoweb** [comment] 2024-08-11 20:33
> No without polling communication with Alexa is one-way. I realized that the problem is not solved, but if you only use notifications via Alexa it's better than nothing...

No Is Better create an automations that reload integrativon every 10 minutes

**Comment by danielbrunt57** [comment] 2024-08-11 20:34
> I had the same problem and I'm following the thread waiting for a solution. But I've found that if I set AMP > three dots > system options > enable new entity additions and enable polling for updates to off, the integration doesn't stop working. It's been running for 4 hours now. I hope it can be useful.

I just tried that and the downside with the enable polling disabled is the last_called attributes are never set this causing the templated entity media_player.alexa_last_called to be unavailable which in turn results in there being no notify.alexa_media_last_called service. If I then run the alexa_media.update_last_service, the templated entity updates and the related notify service appears. So there somehow needs to be at least one occurrence of the polling sequence after restart even if future polling is disabled. Gotta put my thinking cap on again!

**Comment by andrea-git** [comment] 2024-08-11 20:39
> > No, senza sondaggi la comunicazione con Alexa è unidirezionale. Ho capito che il problema non è risolto, ma se usi solo le notifiche tramite Alexa è meglio di niente...
> 
> No È meglio creare automazioni che ricaricano l'integrazione ogni 10 minuti

Don't think so. If you have already an automation that uses Alexa it can be executed meanwhile other task is reloading...

**Comment by chrisvblemos** [comment] 2024-08-11 20:52
> > I had the same problem and I'm following the thread waiting for a solution. But I've found that if I set AMP > three dots > system options > enable new entity additions and enable polling for updates to off, the integration doesn't stop working. It's been running for 4 hours now. I hope it can be useful.
> 
> I just tried that and the downside with the enable polling disabled is the last_called attributes are never set this causing the templated entity media_player.alexa_last_called to be unavailable which in turn results in there being no notify.alexa_media_last_called service. If I then run the alexa_media.update_last_service, the templated entity updates and the related notify service appears. So there somehow needs to be at least one occurrence of the polling sequence after restart even if future polling is disabled. Gotta put my thinking cap on again!

Without polling, we must schedule the HA update manually.
https://developers.home-assistant.io/docs/en/entity_index.html#subscribing-to-updates
        
Found inside the code for _handle_event.

**Comment by antoweb** [comment] 2024-08-11 20:54
> > > No, senza sondaggi la comunicazione con Alexa è unidirezionale. Ho capito che il problema non è risolto, ma se usi solo le notifiche tramite Alexa è meglio di niente...
> > 
> > 
> > No È meglio creare automazioni che ricaricano l'integrazione ogni 10 minuti
> 
> Don't think so. If you have already an automation that uses Alexa it can be executed meanwhile other task is reloading...

?

**Comment by andrea-git** [comment] 2024-08-11 21:02
> > > > No, senza sondaggi la comunicazione con Alexa è unidirezionale. Ho capito che il problema non è risolto, ma se usi solo le notifiche tramite Alexa è meglio di niente...
> > > 
> > > 
> > > No È meglio creare automazioni che ricaricano l'integrazione ogni 10 minuti
> > 
> > 
> > Don't think so. If you have already an automation that uses Alexa it can be executed meanwhile other task is reloading...
> 
> ?

It's simple: 

I THINK you could have some trouble if an automation that uses Alexa and the automation that reload the integration AMP running at the same time

**Comment by danielbrunt57** [comment] 2024-08-13 03:18
> I THINK you could have some trouble if an automation that uses Alexa and the automation that reload the integration AMP running at the same time

Yes that's true as during those several seconds of reloading, the entities don't exist until the reload is finished. If an an automation should trigger during that small window, it will fail.

**Comment by antoweb** [comment] 2024-08-13 06:10
Ok but this cannot be a solution

**Comment by danielbrunt57** [comment] 2024-08-13 08:38
> Without polling, we must schedule the HA update manually. https://developers.home-assistant.io/docs/en/entity_index.html#subscribing-to-updates
> 
> Found inside the code for _handle_event.

That link doesn't work

**Comment by danielbrunt57** [comment] 2024-08-13 08:44
> Ok but this cannot be a solution

"reload" is a 'remove" & "add".  While it is in the removed state, it's entities do not exist in HA.   The solution as I see it is to identify the real issue, fix it, and not have to automate scheduled integration reloads as that is disruptive.

**Comment by antoweb** [comment] 2024-08-13 10:53
> I had the same problem and I'm following the thread waiting for a solution. But I've found that if I set AMP > three dots > system options > enable new entity additions and enable polling for updates to off, the integration doesn't stop working. It's been running for 4 hours now. I hope it can be useful.

Yes you are right buit the solution https://github.com/alandtse/alexa_media_player/issues/2448#issuecomment-2282706890 cannot be definitively

**Comment by antoweb** [comment] 2024-08-13 10:53
> > Ok but this cannot be a solution
> 
> "reload" is a 'remove" & "add". While it is in the removed state, it's entities do not exist in HA. The solution as I see it is to identify the real issue, fix it, and not have to automate scheduled integration reloads as that is disruptive.

Yes you are right buit the solution https://github.com/alandtse/alexa_media_player/issues/2448#issuecomment-2282706890 cannot be definitively

**Comment by danielbrunt57** [comment] 2024-08-16 20:14
Please start with a fresh virgin installation of AMP.
Also see my notes in issue [#2437](https://github.com/alandtse/alexa_media_player/issues/2437#issuecomment-2294062759)

**Comment by deosrc** [comment] 2024-08-16 23:21
I believe my issue is the same as here and #2453.

After upgrading to HA `2024.8.*`, HA was indicating that AMP needed to be reconfigured. I logged into Amazon successfully but the warning persisted. I tried removing the integration (from HA, but not HACS), but I just get the following error when attempting to add it again:

![image](https://github.com/user-attachments/assets/65398b6c-9f8f-4fd8-81fb-584e51daba5a)

I performed the following steps (based on #2437) without success:

1. Uninstall AMP via HACS and restart HA
2. Check for `alexa.*` files in `config/.storage`. I had previously deleted them and they were still not present.
3. Re-install AMP via HACS and restart HA
4. In a private browser window, attempt to re-add the integration. Logging in to Amazon was fine but then the error message above appeared. No pickle file is generated.

I don't seem to get any errors in the HA logs which seems odd. I'll try increasing the logging level and see if I can gather any useful information.

**Comment by danielbrunt57** [comment] 2024-08-16 23:56
> 2. Check for `alexa.*` files in `config/.storage`. I had previously deleted them and they were still not present.

Do not delete all `alexa.*` files in `.storage`!
Just delete the `alexa_media.<your_email>.pickle` file as that is the **_only_** file created by the Alexa Media Player integration.  Any others are from your [Amazon Alexa integration](https://www.home-assistant.io/integrations/alexa/) which exposes HA entities for Alexa to discover and has nothing to do with this Media Player integration.

> 4. In a private browser window, attempt to re-add the integration. Logging in to Amazon was fine but then the error message above appeared. No pickle file is generated.

Why are you using a private browser window???  That is most likely your problem.

**Comment by darioz90** [comment] 2024-08-17 09:33
Some news to fix?
Integration stop after 5/10 min

**Comment by deosrc** [comment] 2024-08-17 09:44
> Do not delete all alexa.* files in .storage!
Just delete the alexa_media.<your_email>.pickle file as that is the only file created by the Alexa Media Player integration. Any others are from your [Amazon Alexa integration](https://www.home-assistant.io/integrations/alexa/) which exposes HA entities for Alexa to discover and has nothing to do with this Media Player integration.

Good to know thanks. I forgot I had that enabled. No harm done as it doesn't get used.

> Why are you using a private browser window??? That is most likely your problem.

Private browser window acts like a fresh browser so no need to clear out my normal browsing cookies, local storage, cache, etc. This is a common ask when debugging and it can be a pain to set everything up again. Especially for something like HA which stores user preferences like themes and sidebar order in local storage rather than on the server side. 

I don't believe there is functionally any difference other than it starts clean and wipes the data at the end of the session.

**Comment by Touch-of-Ink** [comment] 2024-08-17 16:01
> I had the same problem and I'm following the thread waiting for a solution. But I've found that if I set AMP > three dots > system options > enable new entity additions and enable polling for updates to off, the integration doesn't stop working. It's been running for 4 hours now. I hope it can be useful.

I'm in the US. 2FA. I'd been limping along with the 9 minute reboot solution, but unchecking both of those options has worked for me since I tried it yesterday.  Crossing my fingers :) 

What do those two options do?

**Comment by danielbrunt57** [comment] 2024-08-18 02:22
`enable new entity additions`  includes scanning the amazon api  for any new devices added
`enable polling for updates`  enables scanning the amazon api for any changes in existing devices.

I have the 1st one disabled and the 2nd one enabled as just eliminating the 1st one stopped the errors I sometimes saw.

**Comment by danielbrunt57** [comment] 2024-08-18 02:24
> Some news to fix? Integration stop after 5/10 min

@darioz90 No.  I do not see a way to absolutely fix it once and for all, yet...

**Comment by danielbrunt57** [comment] 2024-08-18 02:30
> I don't believe there is functionally any difference

What you might believe might not be what is actual fact.
HA browser in one private tab and Amazon login session in a 2nd private tab may not be sharing it's session cookies with HA.
I do not know how to help you then if you're not willing to do it the way everyone else does...

**Comment by deosrc** [comment] 2024-08-18 15:05
@danielbrunt57 

> What you might believe might not be what is actual fact.

Agreed. I was deliberate in my wording in saying "I believe", and it seems that I was incorrect on some points. Some stored data, such browsing history, [are still present in private mode](https://support.mozilla.org/en-US/kb/common-myths-about-private-browsing?as=u&utm_source=inproduct). It is just that the browsing in private mode is not added to it.

Cookies and local storage are not present though. Using a private window requires me to login to HA again and my user preferences such as theme are not retained. It is not clear if cache is re-used or not.

> HA browser in one private tab and Amazon login session in a 2nd private tab may not be sharing it's session cookies with HA.

There is nothing on the Firefox private tab page or the page linked above to suggest cookies are handled differently in private mode compared with standard, but there is an incognito specific setting for 3rd party cookies in chrome so it's possible. This also reminded me of the [changes to how cookies are handled in firefox](https://support.mozilla.org/en-US/kb/introducing-total-cookie-protection-standard-mode), and also the firefox enhanced tracking protection setting. I don't know if any of this might impact any of the AMP cookies.

> I do not know how to help you then if you're not willing to do it the way everyone else does...

I didn't say I wasn't willing. I would just prefer not to [clear all of my HA user preferences](https://community.home-assistant.io/t/wth-why-most-settings-are-browser-instance-dependant/468419) if it is not necessary and thought private mode might be enough. I had forgotten that I had another browser installed that I could also use, or could use the profiles feature.

I have tested again using a chrome normal window instead of Firefox private window. I don't believe I have ever used this browser, but cleared all browsing data for all sites to be sure (cookies, cache, etc.). The 3rd party cookies setting was set to "Block in incognito mode", so that shouldn't affect this test using a normal window. I received the same "login failed" result.

I can continue testing with other browser scenarios, but it feels like it would be better to try get more information out of HA/AMP instead.

> Respectfully, I fail to see how your current issue is the same as [this issue](https://github.com/alandtse/alexa_media_player/issues/2448#top) or #[2453](https://github.com/alandtse/alexa_media_player/issues/2453)

I'm hesitant to open another "Authentication issue with HA 2024.8.*" thread at the moment when there are already a number of similar issues open, but will do so if you think it best. It seems too much coincidence for another authentication issue in 2024.8.*.

[As mentioned](https://github.com/alandtse/alexa_media_player/issues/2448#issuecomment-2294438989), the auth issue I am having started out the same as #2453. The integration would prompt in HA that it needed to be reconfigured. Clicking reconfigure took me to the AMP Amazon login page where I logged in successfully and the page closed, but the reconfigure prompt persisted. IIRC, it would disappear for less than a second before appearing again.

The "login failed" prompt I have not seen mentioned elsewhere, but is only appearing after I removed and re-added the integration in a hopeful attempt that clearing any data would fix the issue. It also seems odd that I am not getting any error logs at all.

As mentioned above, I'm going to try get more information out of the logging in HA.

**Comment by deosrc** [comment] 2024-08-18 16:22
@danielbrunt57 

From the logs it looks like the issue re-adding the integration is separate and I've opened #2469. I managed to find a workaround to that (included in the issue) and now it is behaving as in #2453. I'll move any discussion there.

**Comment by vincenzo9393** [comment] 2024-08-18 16:29
Stesso problema

**Comment by danielbrunt57** [comment] 2024-08-18 18:54
@deosrc 

Thank you for your carefully detailed response and willingness to try and figure this all out.

**Comment by 1242scooter** [comment] 2024-08-19 23:51
+1

**Comment by Cippo2019** [comment] 2024-08-20 06:20
+1

**Comment by danielbrunt57** [comment] 2024-08-22 19:59
Closing this as it's the same error message as #2453.
Please use that issue moving forward...

**Closed by danielbrunt57** 2024-08-22 19:59 UTC
