### ISSUE TITLE
Can't run automations because notify.alexa_media

### ISSUE THREAD

**Issue by kylewilliams321** [alandtse/alexa_media_player#2329] opened 2024-07-19 20:25 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

The automation "Dog feeding sched - Lunch" (automation.dog_feeding_sched_lunch) has an action that calls an unknown service: notify.alexa_media.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, edit the automation and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version): 
Core
2024.7.2
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240710.0
- alexa_media (version from `const.py` or HA startup): latest version
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

Just stopped working after a network restart, I swapped out and replaced a router with a new one (same ssid and pw)

**Comment by danielbrunt57** [comment] 2024-07-23 15:35
> Just stopped working after a network restart, I swapped out and replaced a router with a new one (same ssid and pw)

- Have you confirmed that your echo's are working normally (i.e. without HA interaction)?
-   - If not, try restarting them as they may be offline.
- Have you tried AMP v4.11.5 (just released)?

**Comment by ChrisHirsch** [comment] 2024-07-23 18:43
Can confirm this is a problem on 4.11.5 too

<img width="588" alt="Screenshot 2024-07-23 at 12 41 33 PM" src="https://github.com/user-attachments/assets/4d4db46e-82d1-4116-bc23-ef7f62ec3260">

Not sure what changed (HA version?). I'll be more than happy to troubleshoot or add details. Let me know what you need.

**Comment by kylewilliams321** [comment] 2024-07-23 19:04
I reinstalled Alexa integration through hacs and think I got it working
again.

**Comment by danielbrunt57** [comment] 2024-07-24 04:28
Please close this issue once you confirm it is working reliably for you.
Thanks.

**Comment by djcrawleravp** [comment] 2024-07-24 04:33
Not working for me, can't run "Good Night" notification.... can you confirm if reinstalling the integration fix the issue?

**Comment by kylewilliams321** [comment] 2024-07-24 11:46
I'll leave open as others appear to have issue still. I think it's still worth looking into and troubleshooting.

**Comment by djcrawleravp** [comment] 2024-07-24 13:25
Just go to the integration, click on "Configure" and then Submit... after that I rebooted my HA instance and everything went normal

**Comment by ChrisHirsch** [comment] 2024-07-24 14:30
So simply clicking on "Configure" and "Submit" did not work. Instead I had to do as @kylewilliams321 suggested and delete and re-install the integration. That seems to have fixed the problem. I was asked for the username, password and 2fa (my account is 2fa) and then I had to restart. 

So this could have been a re-auth issue but I never saw anything in the logs that indicated as such. But this is working again (and thank you for the integration, I use it all the time).

**Comment by Sectorchan** [comment] 2024-07-24 14:41
In my situation, I had to click on reconfigure and enter on the new window my Amazon credentials with 2FA. 
With this, after 2-3 days I have to perform the steps again.

**Comment by danielbrunt57** [comment] 2024-07-24 20:13
> Not working for me, can't run "Good Night" notification.... can you confirm if reinstalling the integration fix the issue?

What does your HA log show for errors?

**Comment by stomko11** [comment] 2024-07-25 16:16
Started to observe similar behavior. I have 2 echo dots connected under my account. One would sporadically lose its media player entity (didn't notice if another one is having the same issue, as I am not using it in any automation, so I don't get that error)
Just happened again, redownloaded AMP and restarted HA and it is back to normal. Prior to last AMP updates, I don't recall ever having such issue.

**Comment by BobMac57** [comment] 2024-07-26 20:14
Having the same issue and tried what others suggested... sometimes it'll fix itself then go back...

**Comment by danielbrunt57** [comment] 2024-07-27 03:08
I'm looking for testers for my current: [`__init__.py`.zip](https://github.com/user-attachments/files/16397905/__init__.py.zip)

**  Note - it is still a WIP but it currently seems to address:

- Extended entities are `unavailable` for the first `10 * scan_interval` seconds if http2push is true until the first poll occurs.
- Error "Too many requests"

I'm curious to know if the changes I have so far are enough to also solve this issue.
If it doesn't help or makes things worse, I'd like to know the details.

Thanks.

**Comment by thorrrr** [comment] 2024-07-27 09:21
HI GUys
Been having this issues for weeks keep pressing repair but 2 to 3 popup each day!
I have to re initiate which works then hit repair each day.
Been running for years so it looks like new issue from Amazon or HA or combination.
I switched on debug and will add on next failure  


Core
2024.7.3
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240710.0

Amazon Alexa 4.11.5

Logger: homeassistant.components.automation.cellar_door_open_notification
Source: helpers/script.py:2002
integration: Automation (documentation, issues)
First occurred: 09:07:56 (1 occurrences)
Last logged: 09:07:56

Cellar Door Open Notification: Error executing script. Service not found for call_service at pos 2: Action notify.alexa_media not found

![image](https://github.com/user-attachments/assets/46c7e62c-8aa3-4f48-ba0b-aa93f0190488)
![image](https://github.com/user-attachments/assets/8b6c6711-5641-4f29-9e90-39eac0565cb5)
![image](https://github.com/user-attachments/assets/8c618f00-b375-4313-bb30-d344b88cae26)

**Comment by thorrrr** [comment] 2024-07-29 16:18
2024-07-29 09:15:40.017 DEBUG (MainThread) [custom_components.alexa_media] 
-------------------------------------------------------------------
alexa_media
Version: 4.12.1
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/alandtse/alexa_media_player/issues
-------------------------------------------------------------------

2024-07-29 09:15:40.017 DEBUG (MainThread) [custom_components.alexa_media] Loaded alexapy==1.27.10
2024-07-29 09:15:40.017 DEBUG (MainThread) [custom_components.alexa_media.helpers] d********n@g*******m: Returning uuid {'uuid': '8771d1d84a4b102bd6e8b5ab7e59e952', 'index': 0}
2024-07-29 09:15:40.041 DEBUG (MainThread) [alexapy.alexalogin] Creating TOTP for Q************************************************OZA
2024-07-29 09:15:40.041 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP Redacted
2024-07-29 09:15:40.041 DEBUG (MainThread) [alexapy.alexalogin] Login created for redacted - amazon.co.uk
2024-07-29 09:15:40.042 DEBUG (MainThread) [alexapy.alexalogin] Searching for cookies from /config/.storage/alexa_media.redacted.pickle
2024-07-29 09:15:40.042 DEBUG (MainThread) [alexapy.alexalogin] Trying to load cookie from file /config/.storage/alexa_media.redacted.pickle
2024-07-29 09:15:40.050 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Alexa Media Player for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 353, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 328, in load_cookie
    cookies = pickle.loads(await myfile.read())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/cookies.py", line 312, in __setitem__
    raise CookieError("Invalid attribute %r" % (K,))
http.cookies.CookieError: Invalid attribute 'partitioned'

**Comment by thorrrr** [comment] 2024-07-29 16:19
2024-07-29 11:28:25.062 ERROR (MainThread) [homeassistant.components.automation.cellar_door_open_notification] Cellar Door Open Notification: Error executing script. Service not found for call_service at pos 2: Action notify.alexa_media not found
2024-07-29 11:28:26.205 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for camera.xiaomi_cloud_map_extractor exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

**Comment by st3v3nFr** [comment] 2024-07-30 12:48
I think this all happen because the integration can't load.
See : https://github.com/alandtse/alexa_media_player/issues/2288
It may help you

**Comment by danielbrunt57** [comment] 2024-08-01 06:54
```
File "/usr/local/lib/python3.12/http/cookies.py", line 312, in setitem
raise CookieError("Invalid attribute %r" % (K,))
http.cookies.CookieError: Invalid attribute 'partitioned'
```

Duplicate of #2288

**Closed by danielbrunt57** 2024-08-01 06:54 UTC

**Comment by thorrrr** [comment] 2024-08-05 13:25
> ```
> File "/usr/local/lib/python3.12/http/cookies.py", line 312, in setitem
> raise CookieError("Invalid attribute %r" % (K,))
> http.cookies.CookieError: Invalid attribute 'partitioned'
> ```
> 
> Duplicate of #2288

HI
Mine is starting i dont think its the same issue my screen  says failing to unload !
