### ISSUE TITLE
Lose Authentication after update - Login causes 500 Response from Amazon

### ISSUE THREAD

**Issue by Tockra** [alandtse/alexa_media_player#2460] opened 2024-08-16 08:05 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After updating the integration I needed to re-authenticate my amazon login. I reached the login page and entered username and password. Then I entered a capture.
After that I got:
<img width="614" alt="image" src="https://github.com/user-attachments/assets/87c60d3b-edde-4df1-b3e2-bf4261c42df4">

**To Reproduce**

1. Install update
2. Re-Auth your account
3. See page at http://192.168.178.140:8123/auth/alexamedia/proxy/verify

**Expected behavior**

it should work

**System details**

- Home-assistant (version): 2024.8.1
- alexa_media (version from `const.py` or HA startup): v4.12.7
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) : yes

**Logs**
There is no button to activate the logging:
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/e512b0ee-351e-411a-adb8-69acb6871b68">

**Comment by Kosztyk** [comment] 2024-08-16 16:52
same here

**Comment by danielbrunt57** [comment] 2024-08-16 19:37
Duplicate of [issue #2437](https://github.com/alandtse/alexa_media_player/issues/2437)

**Closed by danielbrunt57** 2024-08-16 19:37 UTC

**Comment by danielbrunt57** [comment] 2024-08-16 19:40
> Logs
> There is no button to activate the logging:

Never was and never will be a "_button_" to activate logging.

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
