### ISSUE TITLE
Validation of translation placeholders error

### ISSUE THREAD

**Issue by figorr** [alandtse/alexa_media_player#2191] opened 2024-02-17 17:18 UTC
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
Seeing the following error at logs every time I restarted HA after any update.

This bug started at 2024.2. I didn't see it at 2024.1

> Logger: homeassistant.helpers.translation
> Source: helpers/translation.py:288
> First occurred: 17:52:43 (1 occurrences)
> Last logged: 17:52:43
> 
> Validation of translation placeholders for localized (es) string component.alexa_media.config.error.unknown_error failed

**To Reproduce**

Just restartint HA after any update.

**Expected behavior**

I didn't see any extrange behaviour ... just the error.

**System details**

- Home-assistant (version): 2024.2.2
- alexa_media (version from `const.py` or HA startup): 4.9.2
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**

> Logger: homeassistant.helpers.translation
> Source: helpers/translation.py:288
> First occurred: 17:52:43 (1 occurrences)
> Last logged: 17:52:43
> 
> Validation of translation placeholders for localized (es) string component.alexa_media.config.error.unknown_error failed

**Additional context**

**Comment by SrBurner** [comment] 2024-02-18 13:44
Same Here

**Comment by LeidenSpain** [comment] 2024-02-26 16:59
Also to me

**Comment by woempiej** [comment] 2024-02-26 20:17
![afbeelding](https://github.com/alandtse/alexa_media_player/assets/62903344/7ac448ab-74c8-4b5f-9f9a-725ed4b6cda1)

**Comment by bartpijnaert** [comment] 2024-02-26 21:23
i have the same nofification in my log

**Comment by alandtse** [comment] 2024-03-23 18:46
The issue is caused by the fact no one has added a translation in the language. I don't speak those languages. If this bothers you, you need to add the translation. https://github.com/alandtse/alexa_media_player#translations

**Comment by LeidenSpain** [comment] 2024-03-23 22:26
I see the spanish translation is complet
![image](https://github.com/alandtse/alexa_media_player/assets/45803748/01ee5676-b225-4385-a10f-c6eca400ce07)

**Comment by alandtse** [comment] 2024-03-23 22:50
> I see the spanish translation is complet ![image](https://private-user-images.githubusercontent.com/45803748/316272192-01ee5676-b225-4385-a10f-c6eca400ce07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMzQ0NzMsIm5iZiI6MTcxMTIzNDE3MywicGF0aCI6Ii80NTgwMzc0OC8zMTYyNzIxOTItMDFlZTU2NzYtYjIyNS00Mzg1LWExMGYtYzZlY2E0MDBjZTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIyNDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NTg5N2U0ZTFmNjNjZjgyNGYzNmRhZjY3MTJjODE4YWNmNjUwODY0ZjNjMzc3MTI4OTUwM2Y4OGQ1NDczOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9rtYVwVmy7eJ0tmNStOcLY-fzQRzM9J4EGQpPrV9_z0)

Awesome. Thank you. Our next release will include that automatically and the warnings should disappear for Spanish.

**Comment by Apicknet** [comment] 2024-04-19 05:13
When is the update of this error scheduled? I have the same problem.

**Comment by alandtse** [comment] 2024-05-06 03:21
Addressed by pending release.

**Comment by Dacruzzz** [comment] 2024-12-03 16:32
I had the same error for the Dutch language, so I contributed to the translation. If I'm not mistaken, its at 100% now, could you please add it in the next update?

**Comment by danielbrunt57** [comment] 2024-12-03 21:27
> I had the same error for the Dutch language, so I contributed to the translation. If I'm not mistaken, its at 100% now, could you please add it in the next update?

Dutch is NL, correct?
Could you be a little more specific about what and where you contributed?
Thanks.

**Comment by Dacruzzz** [comment] 2024-12-03 22:25
> > I had the same error for the Dutch language, so I contributed to the translation. If I'm not mistaken, its at 100% now, could you please add it in the next update?
> 
> Dutch is NL, correct? Could you be a little more specific about what and where you contributed? Thanks.

Yes, that's correct. You can look at the translations at https://github.com/alandtse/alexa_media_player#translations

**Comment by danielbrunt57** [comment] 2024-12-04 01:44
> Yes, that's correct. You can look at the translations at https://github.com/alandtse/alexa_media_player#translations

I'm trying to read between the lines in your messages and I think you are are telling me that you've contributed NL translations to Lokalise?

**Comment by danielbrunt57** [comment] 2024-12-04 01:50
`nl` looks like it was added 5 months ago?

![image](https://github.com/user-attachments/assets/2c6e7946-583e-4acf-9d69-ad50cfb6434c)

![image](https://github.com/user-attachments/assets/86965961-40cd-4819-adb9-03bb200afe1b)

**Comment by danielbrunt57** [comment] 2024-12-04 01:57
I've never worked on this aspect of AMP so I'm not sure what/where to look...

**Comment by Dacruzzz** [comment] 2024-12-04 08:02
> `nl` looks like it was added 5 months ago?
> 
> ![image](https://private-user-images.githubusercontent.com/49846893/392195531-2c6e7946-583e-4acf-9d69-ad50cfb6434c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyOTk1OTAsIm5iZiI6MTczMzI5OTI5MCwicGF0aCI6Ii80OTg0Njg5My8zOTIxOTU1MzEtMmM2ZTc5NDYtNTgzZS00YWNmLTlkNjktYWQ1MGNmYjY0MzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA4MDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZDA1OWQ4MzhmZmI1ODBkODg0M2ZjOTEzNzc5MTc2NzZmNTgzNTMyMzY3MGFiNTZjYmQ0MWU1MTdkNTU2ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aZyJutsko5UQi-bqPBo3pKVQEXLmbNdm_RkozUPvFEQ) ![image](https://private-user-images.githubusercontent.com/49846893/392195753-86965961-40cd-4819-adb9-03bb200afe1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyOTk1OTAsIm5iZiI6MTczMzI5OTI5MCwicGF0aCI6Ii80OTg0Njg5My8zOTIxOTU3NTMtODY5NjU5NjEtNDBjZC00ODE5LWFkYjktMDNiYjIwMGFmZTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA4MDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YWM5YWY1NmFkMWY3ZmVlNTgxZDdjNWU4OTI4ZDkyMzM3ZWFjYjJlZTI1OGUxNmRkODk0YmQ3YzRkY2U3ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YeFolQNBC8aU9DDASLpmObPHnmFd9x7SSI907TinOCQ) ![image](https://private-user-images.githubusercontent.com/49846893/392196940-82371270-0106-4eb2-b090-5d2634860360.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyOTk1OTAsIm5iZiI6MTczMzI5OTI5MCwicGF0aCI6Ii80OTg0Njg5My8zOTIxOTY5NDAtODIzNzEyNzAtMDEwNi00ZWIyLWIwOTAtNWQyNjM0ODYwMzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA4MDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NDdhNDE5OGYyNTVlMTRjN2U1ZmY5OTZhM2QyYjg0YTZmYjc4M2ViNjczMDQxYWY4ODZmODNlNTQzYjE1YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-pHZtJCULN0LMgT-69kMZFu2TOM0GyR1Vr6vryGC3Mw)

It was added yes, but a lot was still in English, missing or incorrect. So I fixed that.

**Comment by alandtse** [comment] 2024-12-06 05:37
Translations are automatically imported from lokalise on release. There's no reason to revive this old unrelated issue.

**Closed by alandtse** 2024-12-06 05:37 UTC
Labels: bug, lokalise

**Comment by alandtse** [comment] 2024-12-06 17:54
Are you saying you made changes to in lokalize and they didn't propagate in the last release? If so, open a ticket describing that and we can investigate the ci.

**Comment by danielbrunt57** [comment] 2024-12-06 21:18
Thanks Alan.  I'm seeing no English in 5.0.1's `/homeassistant/custom_components/alexa_media/translations/nl.json`.
```
{
  "config": {
    "abort": {
      "forgot_password": "De pagina wachtwoord vergeten is gedetecteerd. Dit is normaal gesproken het gevolg van te veel mislukte aanmeldingen. Amazon kan actie vereisen voordat opnieuw kan worden ingelogd.",
      "login_failed": "Het inloggen van Alexa Mediaspeler is mislukt.",
      "reauth_successful": "Alexa Mediaspeler is met succes opnieuw geverifieerd. Negeer a.u.b. het bericht \"Afgebroken\" van HA."
    },
    "error": {
      "2fa_key_invalid": "Ongeldige ingebouwde 2FA sleutel",
      "connection_error": "Fout bij verbinding; controleer netwerk en probeer opnieuw",
      "identifier_exists": "Dit e-mailadres voor Alexa URL is al geregistreerd",
      "invalid_credentials": "Ongeldige inloggegevens",
      "invalid_url": "De URL is ongeldig: {message}",
      "unable_to_connect_hass_url": "Kan geen verbinding maken met de Home Assistant url. Controleer de externe url onder Configuratie - > Algemeen",
      "unknown_error": "Onbekende fout: {message}"
    },
    "step": {
      "proxy_warning": {
        "data": {
          "proxy_warning": "Negeren en doorgaan - Ik begrijp dat er geen ondersteuning wordt geboden bij inlogproblemen wanneer ik deze waarschuwing  omzeil."
        },
        "description": "De HA server kan geen verbinding maken met de opgegeven URL: {hass_url}.\n> {error}\n\nOm dit op te lossen, moet u bevestigen dat uw **HA server** {hass_url} kan bereiken. Dit veld is  afkomstig van de externe url onder Configuratie -> Algemeen, maar je kunt ook de interne url proberen.\n\nAls je er **zeker** van bent dat jouw client deze url kan bereiken, dan kun je deze waarschuwing negeren.",
        "title": "Alexa Mediaspeler - Kan geen verbinding maken met HA URL"
      },
      "totp_register": {
        "data": {
          "registered": "OTP van de ingebouwde 2FA App Key is succesvol bevestigd."
        },
        "description": "**{email} -Alexa.{url}**\nHeb je met succes een OTP van de ingebouwde 2FA App Key met Amazon bevestigd?  \n >OTP-code {message}",
        "title": "Alexa Mediaspeler - OTP Bevestiging"
      },
      "user": {
        "data": {
          "debug": "Geavanceerde foutopsporing",
          "email": "E-mailadres",
          "exclude_devices": "Uitgesloten apparaten (Scheiding: komma)",
          "extended_entity_discovery": "Inclusief apparaten verbonden via Echo",
          "hass_url": "URL voor toegang tot Home Assistant",
          "include_devices": "Inbegrepen apparaten (Scheiding: komma)",
          "otp_secret": "Ingebouwde 2FA App Key (genereert automatisch 2FA-codes). Deze is niet zes cijfers lang.",
          "password": "Wachtwoord",
          "queue_delay": "Aantal seconden wachten om opdrachten in de wachtrij te groeperen",
          "scan_interval": "Aantal seconden tussen scans",
          "securitycode": "2FA sleutel (aanbevolen om inlogproblemen te voorkomen)",
          "url": "Domeinnaam van Amazon regio (bijv: amazon.co.uk)"
        },
        "description": "Bevestig de onderstaande informatie. Schakel voor oudere configuraties de optie 'Inlogproxymethode gebruiken' uit.",
        "title": "Alexa Mediaspeler - Configuratie"
      }
    }
  },
  "options": {
    "step": {
      "init": {
        "data": {
          "debug": "Geavanceerde foutopsporing",
          "exclude_devices": "Uitgesloten apparaten (Scheiding: komma)",
          "extended_entity_discovery": "Inclusief apparaten verbonden via Echo",
          "hass_url": "Openbare URL voor toegang tot Home Assistant (inclusief afsluitende '/')",
          "include_devices": "Inbegrepen apparaten (Scheiding: komma)",
          "public_url": "Openbare URL voor toegang tot Home Assistant (inclusief afsluitende '/')",
          "queue_delay": "Aantal seconden wachten om opdrachten in de wachtrij te groeperen",
          "scan_interval": "Aantal seconden tussen scans"
        },
        "description": "Vereist *",
        "title": "Alexa Mediaspeler - Herconfiguratie"
      }
    }
  },
  "services": {
    "clear_history": {
      "description": "Wis de laatste items uit de Alexa stemgeschiedenis voor elk Alexa account.",
      "fields": {
        "email": {
          "description": "Accounts om te wissen. Als het veld leeg is, wordt alles gewist.",
          "name": "E-mailadres"
        },
        "entries": {
          "description": "Aantal items om te wissen van 1 tot 50. Als het veld leeg is, verwijder er dan 50.",
          "name": "Aantal items"
        }
      },
      "name": "Wis Amazon stemgeschiedenis"
    },
    "force_logout": {
      "description": "Forceer account om uit te loggen. Voornamelijk gebruikt voor foutopsporing.",
      "fields": {
        "email": {
          "description": "Accounts om te wissen. Als het veld leeg is, wordt alles gewist.",
          "name": "E-mailadres"
        }
      },
      "name": "Uitloggen forceren"
    },
    "update_last_called": {
      "description": "Forceert update van last_called echo apparaat voor elk Alexa-account.",
      "fields": {
        "email": {
          "description": "Lijst met Alexa accounts om bij te werken. Als het veld leeg is, worden alle bekende accounts bijgewerkt.",
          "name": "E-mailadres"
        }
      },
      "name": "Laatst opgeroepen sensor bijwerken"
    }
  }
}
```

**Comment by alandtse** [comment] 2024-12-06 21:32
@danielbrunt57 let me know your lokalize account name and I'll also give you admin rights there. I'm not sure why people are posting that I'm refusing to cede control or whatever.

**Comment by danielbrunt57** [comment] 2024-12-06 21:48
> I'm not sure why people are posting that I'm refusing to cede control or whatever.

I think they are just making assumptions or are somehow ill-informed.  And once one person thinks that way and posts their assumption, others run with it and it snowballs.

Here's my lokalise account:
![image](https://github.com/user-attachments/assets/215d63b2-fdda-4383-94f9-2a29049bdb06)

**Comment by alandtse** [comment] 2024-12-07 08:30
You need to join the AMP team before I can do anything for you.

**Comment by danielbrunt57** [comment] 2024-12-07 10:32
I only have a lokalise free account as as such, I see no option to switch teams.
I don't even recall picking team `HACS` when I signed up...
