### ISSUE TITLE
Alexa integration require re authentication

### ISSUE THREAD

**Issue by meazzaflavio** [alandtse/alexa_media_player#2570] opened 2024-10-01 17:57 UTC
**Describe the bug**

Alexa integration version 4.13.2 always require for reautentication

**To Reproduce**

**Expected behavior**

No reautentication request

**Screenshots**

**System details**

- Home Assistant version:
- alexa_media version "4.13.2"
- Amazon [2FA/2SV enabled]
- Amazon Domain: amazon.it

**Debug Logs (alexa_media & alexapy)**
[home-assistant_alexa_media_2024-10-01T17-45-18.544Z.log](https://github.com/user-attachments/files/17213836/home-assistant_alexa_media_2024-10-01T17-45-18.544Z.log)

**Comment by vbarrientosm** [comment] 2024-10-01 19:07
Try logging in with the option to create a new account (even if you already have one). You will get the error that the account already exists. Then log back in with your existing account and it will allow you to connect. ;)

**Comment by meazzaflavio** [comment] 2024-10-01 19:34
I've tested it and it worked for a while but after some times it require again the reauthentication

**Comment by micium** [comment] 2024-10-01 20:12
https://github.com/alandtse/alexa_media_player/issues/2453

**Comment by bkwar201** [comment] 2024-10-01 22:49
> Try logging in with the option to create a new account (even if you already have one). You will get the error that the account already exists. Then log back in with your existing account and it will allow you to connect. ;)

Thanks for this. I was able to get in this way. Interesting that the U & P are on 1 page which thing redirects to the captcha.
One thing i noticed is that show password didn't work and that it would error out unless i retyped what was there(auto placed from the AMP).
We'll see if it prompts for reauth though...between the initial login and the reauth request issues it sure would be nice to have that fixed.

**Comment by cash83** [comment] 2024-10-02 22:47
I solved it... and for 48 hours that you no longer ask me to authenticate I downgraded the CORE TO VERSION 2024.7.4. I also tried to update to the latest version 2024.10.0 and it always gives the same problem
![Screenshot_20241003-004602](https://github.com/user-attachments/assets/5c80a553-cff7-4c44-bd03-b97c772969ca)
![Screenshot_20241003-004639](https://github.com/user-attachments/assets/bf53e58d-a467-45c7-a23b-1bd63fc7c0c8)

**Comment by alandtse** [comment] 2024-10-03 02:12
Dupe of #2453

**Closed by alandtse** 2024-10-03 02:12 UTC
Labels: duplicate

**Comment by cb12tre** [comment] 2024-10-08 09:14
> I solved it... and for 48 hours you no longer ask me to do authentication with active polling. I downgraded the CORE TO VERSION 2024.7.4. I also tried to update to the latest version 2024.10.0 but it gives the authentication problem ![Screenshot_20241003-004602](https://private-user-images.githubusercontent.com/62354219/373057804-5c80a553-cff7-4c44-bd03-b97c772969ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg4ODQsIm5iZiI6MTcyODM3ODU4NCwicGF0aCI6Ii82MjM1NDIxOS8zNzMwNTc4MDQtNWM4MGE1NTMtY2ZmNy00YzQ0LWJkMDMtYjk3Yzc3Mjk2OWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA5MDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMzc3OTQwYjJhNDc5MDRmMGFkY2NhZDg0YjIzOTZjODJlYzAwZjgyMjNlNzE0OGMwZDY2ZTliYzI4M2Y2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5eoEBsZWI6zvmC0KtN7WRr1qi5RJ7YEQ05PEmZ40PiU) ![Screenshot_20241003-004639](https://private-user-images.githubusercontent.com/62354219/373057833-bf53e58d-a467-45c7-a23b-1bd63fc7c0c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg4ODQsIm5iZiI6MTcyODM3ODU4NCwicGF0aCI6Ii82MjM1NDIxOS8zNzMwNTc4MzMtYmY1M2U1OGQtYTQ2Ny00NWM3LWEyM2ItMWJkNjNmYzdjMGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA5MDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODA2OTE2YTFmODk2MjUxOWFlYjYwNTcyMTc0YjQ5OGU0Y2I5N2ZjMmYxNDhlZDllNzZmYjMzODkyMDJkMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HkvnTGbB6PkCBicESBcBt_BN4ni4exoEEirVwjklAhY)

I solved it the same way a couple of weeks ago. I got tired of the ongoing issues and decided to revert to version 2024.7.4.
With this version of Home Assistant, there are no problems. However, when installing any subsequent version (2024.8, 2024.9, 2024.10), the issue starts to appear.
It seems to be more of an incompatibility problem with the newer versions of Home Assistant rather than a communication issue with the Amazon servers.

**Comment by cash83** [comment] 2024-10-08 10:35
> > Ho risolto... e per 48 ore non mi chiedete più di fare l'autenticazione con polling attivo. Ho fatto il downgrade del CORE ALLA VERSIONE 2024.7.4. Ho anche provato ad aggiornare all'ultima versione 2024.10.0 ma mi dà il problema di autenticazione![Schermata_20241003-004602](https://private-user-images.githubusercontent.com/62354219/373057804-5c80a553-cff7-4c44-bd03-b97c772969ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg4ODQsIm5iZiI6MTcyODM3ODU4NCwicGF0aCI6Ii82MjM1NDIxOS8zNzMwNTc4MDQtNWM4MGE1NTMtY2ZmNy00YzQ0LWJkMDMtYjk3Yzc3Mjk2OWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA5MDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMzc3OTQwYjJhNDc5MDRmMGFkY2NhZDg0YjIzOTZjODJlYzAwZjgyMjNlNzE0OGMwZDY2ZTliYzI4M2Y2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5eoEBsZWI6zvmC0KtN7WRr1qi5RJ7YEQ05PEmZ40PiU) ![Schermata_20241003-004639](https://private-user-images.githubusercontent.com/62354219/373057833-bf53e58d-a467-45c7-a23b-1bd63fc7c0c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg4ODQsIm5iZiI6MTcyODM3ODU4NCwicGF0aCI6Ii82MjM1NDIxOS8zNzMwNTc4MzMtYmY1M2U1OGQtYTQ2Ny00NWM3LWEyM2ItMWJkNjNmYzdjMGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA5MDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODA2OTE2YTFmODk2MjUxOWFlYjYwNTcyMTc0YjQ5OGU0Y2I5N2ZjMmYxNDhlZDllNzZmYjMzODkyMDJkMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HkvnTGbB6PkCBicESBcBt_BN4ni4exoEEirVwjklAhY)
> 
> L'ho risolto allo stesso modo un paio di settimane fa. Mi sono stancato dei problemi in corso e ho deciso di tornare alla versione 2024.7.4. Con questa versione di Home Assistant, non ci sono problemi. Tuttavia, quando si installa una versione successiva (2024.8, 2024.9, 2024.10), il problema inizia a presentarsi. Sembra essere più un problema di incompatibilità con le versioni più recenti di Home Assistant piuttosto che un problema di comunicazione con i server Amazon.

the problem with the latest version HA Amp seems to be solved

**Comment by cash83** [comment] 2024-10-09 08:21
> > > > Ho risolto... e per 48 ore non mi chiedete più di fare l'autenticazione con polling attivo. Ho fatto il downgrade del CORE ALLA VERSIONE 2024.7.4. Ho anche provato ad aggiornare all'ultima versione 2024.10.0 ma mi dà il problema di autenticazione![Schermata_20241003-004602](https://private-user-images.githubusercontent.com/62354219/373057804-5c80a553-cff7-4c44-bd03-b97c772969ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg4ODQsIm5iZiI6MTcyODM3ODU4NCwicGF0aCI6Ii82MjM1NDIxOS8zNzMwNTc4MDQtNWM4MGE1NTMtY2ZmNy00YzQ0LWJkMDMtYjk3Yzc3Mjk2OWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA5MDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMzc3OTQwYjJhNDc5MDRmMGFkY2NhZDg0YjIzOTZjODJlYzAwZjgyMjNlNzE0OGMwZDY2ZTliYzI4M2Y2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5eoEBsZWI6zvmC0KtN7WRr1qi5RJ7YEQ05PEmZ40PiU) ![Schermata_20241003-004639](https://private-user-images.githubusercontent.com/62354219/373057833-bf53e58d-a467-45c7-a23b-1bd63fc7c0c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg4ODQsIm5iZiI6MTcyODM3ODU4NCwicGF0aCI6Ii82MjM1NDIxOS8zNzMwNTc4MzMtYmY1M2U1OGQtYTQ2Ny00NWM3LWEyM2ItMWJkNjNmYzdjMGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA5MDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODA2OTE2YTFmODk2MjUxOWFlYjYwNTcyMTc0YjQ5OGU0Y2I5N2ZjMmYxNDhlZDllNzZmYjMzODkyMDJkMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HkvnTGbB6PkCBicESBcBt_BN4ni4exoEEirVwjklAhY)
> > > 
> > > 
> > > L'ho risolto allo stesso modo un paio di settimane fa. Mi sono stancato dei problemi in corso e ho deciso di tornare alla versione 2024.7.4. Con questa versione di Home Assistant, non ci sono problemi. Tuttavia, quando si installa una versione successiva (2024.8, 2024.9, 2024.10), il problema inizia a presentarsi. Sembra essere più un problema di incompatibilità con le versioni più recenti di Home Assistant piuttosto che un problema di comunicazione con i server Amazon.
> > 
> > 
> > il problema con l'ultima versione HA Amp sembra essere risolto
> 
> No, ho provato qualche giorno fa con Home Assistant 2024.10.1 e Alexa Media Player 4.13.4 e il problema persisteva.

I've been on the latest version for 2 or 3 days and I'm not having any problems. Try updating HA from the terminal, that's what I did.

**Comment by cb12tre** [comment] 2024-10-09 12:16
> > > > > Ho risolto... e per 48 ore non mi chiedete più di fare l'autenticazione con polling attivo. Ho fatto il downgrade del CORE ALLA VERSIONE 2024.7.4. Ho anche provato ad aggiornare all'ultima versione 2024.10.0 ma mi dà il problema di autenticazione![Schermata_20241003-004602](https://private-user-images.githubusercontent.com/62354219/373057804-5c80a553-cff7-4c44-bd03-b97c772969ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg4ODQsIm5iZiI6MTcyODM3ODU4NCwicGF0aCI6Ii82MjM1NDIxOS8zNzMwNTc4MDQtNWM4MGE1NTMtY2ZmNy00YzQ0LWJkMDMtYjk3Yzc3Mjk2OWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA5MDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMzc3OTQwYjJhNDc5MDRmMGFkY2NhZDg0YjIzOTZjODJlYzAwZjgyMjNlNzE0OGMwZDY2ZTliYzI4M2Y2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5eoEBsZWI6zvmC0KtN7WRr1qi5RJ7YEQ05PEmZ40PiU) ![Schermata_20241003-004639](https://private-user-images.githubusercontent.com/62354219/373057833-bf53e58d-a467-45c7-a23b-1bd63fc7c0c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg4ODQsIm5iZiI6MTcyODM3ODU4NCwicGF0aCI6Ii82MjM1NDIxOS8zNzMwNTc4MzMtYmY1M2U1OGQtYTQ2Ny00NWM3LWEyM2ItMWJkNjNmYzdjMGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA5MDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODA2OTE2YTFmODk2MjUxOWFlYjYwNTcyMTc0YjQ5OGU0Y2I5N2ZjMmYxNDhlZDllNzZmYjMzODkyMDJkMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HkvnTGbB6PkCBicESBcBt_BN4ni4exoEEirVwjklAhY)
> > > > 
> > > > 
> > > > L'ho risolto allo stesso modo un paio di settimane fa. Mi sono stancato dei problemi in corso e ho deciso di tornare alla versione 2024.7.4. Con questa versione di Home Assistant, non ci sono problemi. Tuttavia, quando si installa una versione successiva (2024.8, 2024.9, 2024.10), il problema inizia a presentarsi. Sembra essere più un problema di incompatibilità con le versioni più recenti di Home Assistant piuttosto che un problema di comunicazione con i server Amazon.
> > > 
> > > 
> > > il problema con l'ultima versione HA Amp sembra essere risolto
> > 
> > 
> > No, ho provato qualche giorno fa con Home Assistant 2024.10.1 e Alexa Media Player 4.13.4 e il problema persisteva.
> 
> I've been on the latest version for 2 or 3 days and I'm not having any problems. Try updating HA from the terminal, that's what I did.

I tried to update manually as you suggested. I completely removed 'Alexa Media Player' and reconfigured it, but after a few minutes the errors started again, for example this one:

Registratore: homeassistant
Fonte: /usr/src/homeassistant/homeassistant/runner.py:147
Prima occorrenza: 14:07:39 (1 occorrenze)
Ultima registrazione: 14:07:39

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 889, in send_tts
    await self.send_sequence(
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 512, in send_sequence
    await self.run_behavior(node_data, queue_delay=queue_delay)
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 434, in run_behavior
    await self._post_request("/api/behaviors/preview", data=data)
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 226, in _post_request
    return await self._request("post", uri, data, query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 199, in _request
    raise AlexapyLoginError("Login error detected; not contacting API")
alexapy.errors.AlexapyLoginError: Login error detected; not contacting API
